### ISSUE TITLE
No route matches {:controller=>"gitolite_public_keys", :id=>1, :action=>"delete"}

### ISSUE THREAD

**Issue by zulus** [kubitron/redmine_git_hosting#10]
This problem is on latest redmine : 1.3.1

Processing MyController#account (for 83.5.90.217 at 2012-02-06 18:55:12) [GET]
  Parameters: {"action"=>"account", "controller"=>"my"}
Rendering template within layouts/base
Rendering my/account

ActionView::TemplateError (No route matches {:controller=>"gitolite_public_keys", :id=>1, :action=>"delete"}) on line #59 of vendor/plugins/redmine_git_hosting/app/views/my/account.rhtml:
56:                 <td><%= h(key) %></td>
57:                 <td class="buttons">
58:                     <%= link_to(l(:button_edit),   { :controller => 'gitolite_public_keys', :action => 'edit', :id => key.id }, :class => 'icon icon-edit') %>
59:                     <%= link_to(l(:button_delete), { :controller => 'gitolite_public_keys', :action => 'delete', :id => key.id }, :class => 'icon icon-del') %>
60:                 </td>
61:             </tr>
62:         <% end %>

```
vendor/plugins/redmine_git_hosting/app/views/my/account.rhtml:59:in `_run_rhtml_vendor47plugins47redmine_git_hosting47app47views47my47account46rhtml'
vendor/plugins/redmine_git_hosting/app/views/my/account.rhtml:54:in `each'
vendor/plugins/redmine_git_hosting/app/views/my/account.rhtml:54:in `_run_rhtml_vendor47plugins47redmine_git_hosting47app47views47my47account46rhtml'
/usr/lib/ruby/1.8/phusion_passenger/rack/request_handler.rb:92:in `process_request'
/usr/lib/ruby/1.8/phusion_passenger/abstract_request_handler.rb:207:in `main_loop'
/usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:418:in `start_request_handler'
/usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:358:in `handle_spawn_application'
/usr/lib/ruby/1.8/phusion_passenger/utils.rb:184:in `safe_fork'
/usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:354:in `handle_spawn_application'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `__send__'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `main_loop'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:163:in `start'
/usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:213:in `start'
/usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:262:in `spawn_rails_application'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:126:in `lookup_or_add'
/usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:256:in `spawn_rails_application'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:80:in `synchronize'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
/usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:255:in `spawn_rails_application'
/usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:154:in `spawn_application'
/usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:287:in `handle_spawn_application'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `__send__'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `main_loop'
/usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
/usr/lib/phusion_passenger/passenger-spawn-server:61
```

**Comment by kubitron** [comment]
Hello.  Which version of the plugin are you using?  

The latest version of my plugin (my master branch here) was updated for 1.3.x.  I just tried updating from 1.3.0=>1.3.1, and it seems to work fine.  Can you tell me more about your environment?

If you are using Ericb's version of the plugin, it is known not to work with 1.3.x.

**Comment by zulus** [comment]
I have your latest branch (from today).

My env:
ubuntu 11.04 x86-64, redmine 1.3.1 (SVN tag), mysql 5.1

what information you need?

**Comment by kubitron** [comment]
Which branch?  It appears from that error message that you are not using the master branch, but rather one of the other branches.  The reason that I say this, is that the master branch no longer has:

```
app/views/my/account.rhtml
```

Instead, it has:

```
app/views/my/account.html.erb
```

Are you _sure_ you are on the master branch?  (that is the only branch that works with 1.3.x).

**Comment by kubitron** [comment]
[ I meant on "my master branch" for the plugin]

**Comment by kubitron** [comment]
Ping?  Any answers to the above question?  I want to close this out (if it is simply the wrong branch) or fix this bug. I cannot reproduce at the moment...

**Comment by zulus** [comment]
I just used:
`git clone git://github.com/kubitron/redmine_git_hosting.git` but something went wrong :P

15min ago I was reinstall plugin and now work correctly sorry.

**Comment by kubitron** [comment]
Hm... Are you able to go to the "my account" page?  Does that work?

**Comment by zulus** [comment]
Now yes. I can edit/remove my keys. Again sorry for stupid ticket (I'm after migration from gitosis to gitolite).

**Comment by kubitron** [comment]
No worries.  Always happy when a problem resolution doesn't require work on my part.  Good luck.
