### ISSUE TITLE
Multiple repo support branch dropdown always goes to main repo.

### ISSUE THREAD

**Issue by Thalagyrt** [kubitron/redmine_git_hosting#100]
As an example, I see a project here in my install that has two repos, kiaronetwork and kiarovideo. Kiaronetwork is the main repo, and kiarovideo is a secondary repo on the project. Each project has two branches: master, and develop.

When selecting kiarovideo in the repositories list off to the right in the repositories tab, and then trying to switch to the develop branch, the form directs to the following URL, showing the develop branch of the main branch (kiaronetwork):

https://<snip>/projects/kiaroengine/repository/show?rev=develop

It seems it should direct to the following, if working properly, as this following URL shows the develop branch of the kiarovideo repository.

https://<snip>/projects/kiaroengine/repository/kiarovideo?rev=develop

It seems related to this line in app/views/repositories/_navigation.html.erb, but I'm no rails expert; I'm a django guy, so I'm really unsure how to fix it. I'll play around with it a bit though and if I come up with a fix I'll submit a patch:

<% form_tag({:action => controller.action_name, :id => @project, :path => to_path_param(@path), :rev => ''}, {:method => :get, :id => 'revision_selector'}) do -%>

This is generating a form with an action pointing to repository/show as opposed to repository/kiarovideo as it should.

Hope this helps a bit!

**Comment by Thalagyrt** [comment]
I have a dirty fix at the very least for someone who stumbles upon this. It doesn't maintain the pretty URL (I tried that via adding :repository_id to form_tag, but for some reason it was still generating show instead of the repo url).

I simply added the following right below the rev text_field_tag in the template mentioned above:

<%= hidden_field_tag 'repository_id', @repository.identifier_param %>

Ugly URLs, but it's functional! Might be a stepping point for someone more familiar with the ruby stack to fix this, dunno! :)

**Comment by kubitron** [comment]
Can you give more information about your installation?  Run ./script/about at the top level of your redmine installation.... (don't forget to set the RAILS_ENV variable first):

```
export RAILS_ENV=production
./script/about
```

**Comment by Thalagyrt** [comment]
Sure, no problem. Here you go!

redmine@source:~$ RAILS_ENV=production ./script/about
NOTE: Gem.source_index is deprecated, use Specification. It will be removed on or after 2011-11-01.
Gem.source_index called from /opt/redmine/config/../vendor/rails/railties/lib/rails/gem_dependency.rb:21.
/opt/redmine/lib/redmine/scm/adapters/git_adapter.rb:26: warning: already initialized constant GIT_BIN
About your application's environment
Ruby version              1.8.7 (x86_64-linux)
RubyGems version          1.8.15
Rack version              1.1.4
Rails version             2.3.15
Active Record version     2.3.15
Active Resource version   2.3.15
Action Mailer version     2.3.15
Active Support version    2.3.15
Edge Rails revision       unknown
Application root          /opt/redmine
Environment               production
Database adapter          mysql
Database schema version   20120904060609

About your Redmine plugins
Advanced roadmap & milestones plugin   0.7.0
Redmine Better Gantt Chart plugin      0.6.5
Redmine Git Hosting Plugin             0.5.1x

**Comment by kubitron** [comment]
Ok.  Can you try pulling from head of master and see if this fixes things?  There was a weird, long-running bug from before I took over the plugin (I think).  If this fixes your problem, please close out the bug.

**Comment by Thalagyrt** [comment]
Sorry about the late reply, came down with the flu. The changeset you committed definitely fixed the issue I was seeing in a much more elegant way than my hack of a fix. If there's any way I can buy you a beer or something as a token of gratitude for your work on this plugin, let me know! It's really made my life a bit easier the past 5-6 months since I set it up. :)

**Comment by kubitron** [comment]
Glad to hear that this has been useful!  No beer necessary.
