### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by clintberry** [kubitron/redmine_git_hosting#11]
I followed the install directions and am getting a 401 when using http protocol and when using ssh it is asking me for a password for git@myserver and when I enter in the password for the git user on the box it is saying myrepo.git does not appear to be a git repository. 

Any suggestions as to what I might have done wrong?

**Comment by clintberry** [comment]
FYI, the plugin installed fine and I get all the green check marks in the configuration page of the plugin. I also tested gitolite by cloning the admin repo using the ssh key that I installed in the redmine_git_hosting plugin. It worked fine. So strange.

**Comment by kubitron** [comment]
Which version of the plugin are you using?  Mine?

You have having two completely separate problems (the http and ssh paths are very separate).  With respect to the http protocol, are you using apache+fcgi?  I had to do something like the following (look at the rewrite rule) in order for passwords to get passed through to Redmine/the plugin.

<pre>
<Location /redmine>
    RewriteEngine On
    # Let apache handle purely static files like images by itself.
    RewriteCond %{REQUEST_FILENAME} !-f

    # Send Everything else to Typo
    RewriteRule ^(.*)$ dispatch.fcgi [E=X-HTTP_AUTHORIZATION:%{HTTP:Authorization},QSA,L]
</Location>
</pre>


With respect to ssh, you should never be asked for a password.  It should either pass you right through or ask for a pass-phrase (if you choose to put one on your key).  Did you upload a public key to your "my account" page of your user account?  Make sure that you copy everything from your choosen id_rsa.pub file (including the leading "ssh-rsa"). Secondly, are you sure that the private half of that key is available from the account that you are cloning from (e.g.  the ~/.ssh/id_rsa file)?  Does it have the right permissions?  (i.e. 700 for ~/.ssh and 400 for ~/.ssh/id_rsa)?  Finally, are you sure that your user account is in the membership list for some project that has a gitolite-managed repository?

You can test your ssh key configuration (assuming that the above questions are in the affirmative) with:

```
ssh git@myserver
```

This will give you a report about what repositories you have access to...

**Comment by clintberry** [comment]
I am using yours for sure. You seem to be much more active on here :-)

For ssh, I added the public key to my user in chiliproject (version 2.6.0) and I just double checked that it is all copied correctly.

The place I am cloning from has the correct private key and has the correct permissions.

I just logged in to my chiliproject server via ssh using the git user and password and I can get in fine. I can even see the repositories folder and see my project's repository. I also just tested the sudo command, but when I enter sudo it is asking for my password. Shouldn't it not ever ask for my password?

**Comment by clintberry** [comment]
I checked the logs for apache and saw this baby:

To git@pmddevlinux:gitolite-admin.git
   6abc213..5a3957c  master -> master
fatal: bad default revision 'HEAD'
fatal: Not a valid object name HEAD:

Have you ever seen that before?

**Comment by kubitron** [comment]
With respect to previous error referencing "HEAD", perhaps you have not made any commits to the repository yet?  I've seen something similar before if you try to clone a completely empty repo.  (Click on the repository link in Chili and follow the instructions, if this is the case).

With respect to ssh keys, re-clone/pull the gitolite-admin repository and look to see if the config file looks correct.  Looks in the keydir directory and see if your user key is there or not...  One thing that can mess you up is if the user key you use to try to access repositories is the same as the gitolite-admin key.  In this case, gitolite won't be able to tell the admin from the user...  

What I mean by running 

```
ssh git@myserver
```

is not to be in a context that has access to the root key, but rather one that would use your user key.  This command _should not_ log you in, but rather should only give you a summary of your access capabilities.

**Comment by clintberry** [comment]
Thank you so much for your help. Here is my update:

I switched my personal key for the git admin key and cloned the gitolite admin repo. It cloned fine and I looked in the config. I see my new project's git repo in there, but it is only giving read access to "daemon". I also checked the keys directory and the only key in there is the gitolite_admin_id_rsa key that I created on setup. Does that mean the plugin isn't adding my personal key correctly?

My personal key is different than the gitolite admin key.

If I have to edit the gitolite config manually I will. Will that break your redmine plugin?

**Comment by clintberry** [comment]
Hmmm, well I created a new project and added a git repo and it isn't showing up. I must have broken something. I will reinstall and get back to you.

**Comment by clintberry** [comment]
Okay, I reinstalled, and I am still having the same problem. Does this plugin have its own error logging somewhere? When I create repos in project settings it doesn't actually create them in gitolite. 

I tested ssh git@myserver and indeed it returns access privs for the user.

When I run RAILS_ENV=production rake gitolite:update_repositories as www-data user it returns nothing, but does not error out.

**Comment by kubitron** [comment]
There is very extensive logging in redmine_root/log/production.log.  This is one of the things that I changed when I took over the plugin.  Take a look there.  You should try running:

```
tail -f log/production.log
```

while you are performing operations.  For instance, try adding and removing user keys, removing a user from the member list of a project, etc.  

Do you think that the primary issue is that new projects are not created, but that you can add and remove people from the membership list?

You may be running into an incompatibility with Chili -- there have been others that have ultimately given up and gone with Redmine and things started working.  If it turns out that there is an incompatibility, I can try to help you through it, but...

Make sure that you run (very important):

```
rake db:migrate_plugins 
```

Did you do this after installing the plugin?

**Comment by clintberry** [comment]
I definitely did the migrate_plugins command. I am going to give it one more go, but I am going to go ahead and try it with redmine after that. If others have had success, then it is worth a shot.

**Comment by clintberry** [comment]
What version of ChiliProject would you recommend if I chose chili project?

**Comment by kubitron** [comment]
Do you mean Redmime?  I would say 1.3.1.

**Comment by clintberry** [comment]
Good progress for me! I reinstalled chili project one last time to see, and reinstalled the plugin. Now when I add a repo, I can see it in the gitolite admin repo, and when I add a key in my user profile it adds it to the gitolite admin repo as well! Yay!
Here is how it looks in the gitolite admin config file:

```
repo    mymediconnect
    R       =       daemon
    RW+     =       redmine_cberry_1328656033_805410
```

Now I only have one problem left, when I go to push to this repo, it tells me:

```
W access for yourepo DENIED to cberry
```

I think I have seen others with this issue, so I will go searching. Thanks so much for you help!

**Comment by clintberry** [comment]
It looks like I had an old public key in the gitosis admin repo that matched my current one. I deleted it and all is well now! This plugin is awesome! I should learn ruby so I can help maintain it with you.

**Comment by kubitron** [comment]
Say -- Any chance that you could debug Chili a bit before switching?  I am curious what doesn't work.  And -- in particular, does running "fetch_changesets" fix everything?  If the answer is "yes", then this is a simple problem with fielding events during initial operations. I could believe that I haven't hooked into the latest version of Chili correctly.

I have designed fetch_changesets so that I can correct a wide variety of problems.  I am hoping that it fixes yours...  (also, you should watch the log while you do that to see what is being done).

**Comment by clintberry** [comment]
Sure, I can help you out. FYI, I ended up running ChiliProject v2.5.0 this last time and that is probably why it started working for me. If you would like, I would be happy to reinstall on ChiliProject v2.7 or even v.3.0 which they made stable today and see what the log says. 

Currently I can push changes on v2.5 but when trying to view the repo I get a server error and when trying to run fetch_changeset I get an error as well with a LOOOONG output of numbers. Anyway, let me know which version you want me to debug and I will make it happen.

**Comment by kubitron** [comment]
Did you get the 401 problem fixed?

Also, are you setting up fetch_changesets to run regularly?  Probably should do that.

For my understanding, which version of Chili is working for you?

**Comment by clintberry** [comment]
Here is my current status: I have chiliproject v2.5.0 running and have installed your latest plugin

The plugin is correctly updating the gitolite admin repo with keys and configuration, so that is awesome.

When I try to view the repo in chili I get a server error, and when I try to run fetch_changesets I get the same error:

https://gist.github.com/1763042

That shows that there is a HUGE number trying to be inserted into the database and it doesn't like it and that is what is causing me grief. Everything else is working.

**Comment by kubitron** [comment]
Ok.  I would say to open a new issue about the fetch_changesets not working.  Give me all of the info, and paste in the resulting log (give me a complete "paragraph" from the log, which starts with a Rails controller entry and end at the next entry.  You can cut and paste it directly into the issue box by surrounding it with <pre> and </pre>.  I'd like to see what is wrong.  (I think that the problem with the repository link and fetch_changesets is probably the same thing).

**Comment by kubitron** [comment]
Ah.   This is likely one of two things, both caused by the plugin caching mechanism:  (1) you need to tell your database that it is ok to put large data entries into it (for instance, with mysql, need to set the "max_allowed_packet" in /etc/my.cnf, I have mine set to 32M).  (2) You may need to modify your "max_cache_element_size" parameter on the plugin settings page.

I would start with #1.

**Comment by clintberry** [comment]
#1 did the trick! You are the man! Seriously though, I would love to help you debug on any system. Do you want me to install the newest stable chili and run through the install and see what happens?

**Comment by kubitron** [comment]
Glad to hear that it worked!  I should really put that in the README.

If you are up to trying on versions of Chili, go for it.  What version were you originally having problems with?  I'm a bit unclear why it started working for you... Also, did you ever get smart HTTP working?

**Comment by clintberry** [comment]
So my original chili was version 2.7.0 and the reason it didn't work was because I renamed my private and public keys for the git user to gitolite_admin_id_rsa and gitolite_admin_id_rsa.pub which meant that the git user wasn't actually using those keys anymore. So user error. But when I noticed the problem and fixed it, it didn't make things work, I had to do a complete re-install. 

I didn't get smart HTTP working and I am not sure why. When I installed redmine with Turneky Linux, smart http worked great, so I will compare my apache configs and see what the difference is.

**Comment by kubitron** [comment]
Say -- would you be willing to try Chili 2.7?  I am curious what is not working...

**Comment by clintberry** [comment]
sure thing. i will test tomorrow on ubuntu.

**Comment by kubitron** [comment]
Anything new on this front?  Have you verified that there is a problem with Chili 2.7/3.0?  Also, is Chili 2.5 still working for you?

**Comment by clintberry** [comment]
No problem with Chili 2.7 so far when following the directions exactly, but I haven't done thorough testing yet. We run on 2.5 for all our projects daily and it is working like a charm. Very cool so far. I haven't installed on 3.0 yet, but will soon.

**Comment by kubitron** [comment]
Ah... any thought why it wasn't working with 2.7 before?  I've had isolated instances of people who ultimately gave up on Chili and moved to Redmine to make things work...  

Is the administrator able to look at users public keys properly?  (That is functionality that I added along with the Redmine 1.3 compatibility upgrades...)

**Comment by clintberry** [comment]
On 2.7 I messed up the public key file for the git user by re-naming it to gitolite_admin_id_rsa.pub in the git user's .ssh directory, so it no longer had a key essentially. Idiotic, I know.

I am so glad you told me about the admin being able to see other users public keys. Yes it works on 2.5! I will find out about 2.7 and 3.0 when I install it.

**Comment by kubitron** [comment]
Can you verify that a "fetch_changesets" operation triggers a "RESYNC_ALL" in the plugin?  You should see something like this in the log (from Redmine, but should be similar):

```
Processing SysController#fetch_changesets (for 128.32.37.213 at 2012-02-22 13:30:01) [GET]  Parameters: {"key"=>"elsP2QBqLKh6UclLlP2B"}
Executing RESYNC_ALL operation on gitolite configuration
Fetching changes from gitolite-admin repository to /tmp/redmine_git_hosting/git-tess/gitolite-admin
Our hook is already installed
Completed in 1802ms (View: 0, DB: 63) | 200 OK [https://tessellation.cs.berkeley.edu/redmine/sys/fetch_changesets?key=elsP2QBqLKh6UclLlP2B]
```

Notice the "RESYNC_ALL" in the log....

**Comment by kubitron** [comment]
(p.s. I'm curious about whatever version of Chili you have running -- I have someone playing with 3.0 and not clear if it is tied into fetch_changesets properly or not...).  I'm certainly curious about 2.5 and/or 2.7.
