### ISSUE TITLE
[FEATURE] Toggle HTTPS access globally

### ISSUE THREAD

**Issue by phindmarsh** [kubitron/redmine_git_hosting#14]
We don't use (and have no reason to) the Smart HTTP access, it would be sweet if there was an option in the plugin configuration to disable it for new projects all the time.

**Comment by kubitron** [comment]
Ah...  Seems like a reasonable request....

**Comment by phindmarsh** [comment]
I imagine a 'Disabled by default' option would suffice :)

Thanks!

**Comment by kubitron** [comment]
Ok.  I realize that it has been a long time (things got busy somehow).  However, try the latest commit on my master branch.  It adds default settings for the three repository access options (daemon, HTTPS, and CIA) on the plugin settings page.  

See if this works for you.... (don't forget to run db:migrate_plugins!).

**Comment by phindmarsh** [comment]
At this stage it seems to work sweet.

Had to make the /bin directory again (was throwing internal errors until it was there), but other than that all seamless!

Thanks for all the hard work :)

**Comment by kubitron** [comment]
Um... Is your /bin directory not normally writeable by the web server?

**Comment by phindmarsh** [comment]
It appears each time I pull from the repository the ./bin directory is removed. If I mkdir bin then chown it it works fine, its not a major at all.

I have redmine installed via apt-get on ubuntu 10.04 which places it in /usr/share/redmine

**Comment by kubitron** [comment]
Two questions:

1) Do you execute:

```
rake db:migrate_plugins
```

every time you pull?

2) Is the root of the plugin not normally writeable by the web server?  If so, you should look at the new README about binaries. I suggest an alternative approach for you:

```
rake redmine_git_hosting:install_scripts RAILS_ENV=production
```

This will build the scripts for you.  I'd execute it after you do the db:migrate_plugins.

**Comment by phindmarsh** [comment]
1) Yes (provided I remember to :P)

2) Great, I didn't know that existed, I'll use that from now on. 

Thanks for your support!

**Comment by kubitron** [comment]
(2) Well, the ability to build the scripts directory from the command line was always there for selinux, but I just made it more usable (for the common man?) with the last commit.  Take a look at the new section in the README on the scripts directory.  Let me know if it is confusing or not.

Just to follow up: I am assuming that the issue with the bin directory is not new, but rather something that has always been there for you....?  I'd love to make this just work for people (one last thing to not worry about). Can you tell me about the ownership and permissions of the top-level plugin directory when you download a fresh release?  Also, what user is your web server run as?

Finally -- after you decide that this feature request is filled, could you close it?  (but only after you make sure that it does what you needed).

**Comment by phindmarsh** [comment]
The ./bin thing is something different so I'll close this one and make another to keep it separate.
