### ISSUE TITLE
addition of ssh-key for sub-project fails

### ISSUE THREAD

**Issue by gituser** [kubitron/redmine_git_hosting#19]
https://github.com/ericpaulbishop/redmine_git_hosting/issues/154

**Comment by kubitron** [comment]
I don't seem to be able to reproduce this problem.  What I did was:

Create the root project with the automatic git repo creation turned off.
Create a sub-project with automatic git repo creation turned on.

This created the second project properly in a sub-directory of the repository.  It also added the redmine administrator key to the conf/gitolite.conf file.

Can you give me more info about (1) how to reproduce your problem (what is the exact sequence of events you do).  and (2) give me the log file output from log/production.log during the operations you did and (3) show me what the resulting conf/gitolite.conf file is?

**Comment by gituser** [comment]
I will try to do this! however, currently I'm already using root project's repository configured.

If I try to delete it and after that re-create, will I lose any changes ?

Thanks.

**Comment by gituser** [comment]
weird, but I've just tested with a recently new created project and it worked..

could it be because at first I tried eric's plugin (it happened there).

after that I've upgraded to yours version and it also happened first time, after that I completely reinstalled gitolite and removed existing repos and it worked..

anyways thanks for your great work, I think this can be solved.

**Comment by kubitron** [comment]
Glad to hear it!  I completely rewrote the path code for my version of the plugin...  Let me know if this problem reappears...
