### ISSUE TITLE
Branches/Commits not visible

### ISSUE THREAD

**Issue by pcaddict** [kubitron/redmine_git_hosting#20]
I do not know if this issue is related to this plugin or redmine itself. If this is a redmine issue please delete.

I am running a redmine 1.3.1 stable installation with passenger + apache. After a project is created (having"Automatically initialize Git Repositories for new projects" enabled) the repository is initialized and the instructions to complete the process are presented. After completing the initialization process and pushing the repository to the server, the repository tab under the project shows the committed file but no branch information. Also, when a branch is created and pushed to the server it is not shown in the typical fashion with the drop down branch selection.

The only way I have successfully gotten the repositories tab to show new branches and commits is by deleting and recreating the project with the same identifier. I have followed the directions in the 'Resychronization of gitolite configuration' of the instructions, specifically executing fetch_changesets() from a URL. Below is the output in production.log:

Processing SysController#fetch_changesets (for 192.168.2.1 at 2012-02-23 22:55:44) [GET]
  Parameters: {"key"=>"<key here>"}
Executing RESYNC_ALL operation on gitolite configuration
Cloning gitolite-admin repository to /tmp/redmine_git_hosting/git/gitolite-admin
Our hook is already installed
Completed in 2187ms (View: 0, DB: 3) | 200 OK [http://redmine.dcslns.com/sys/fetch_changesets?key=<key here>

This does not appear to have any effect on what I am able to view on the repositories tab. Fetch commits automatically is enabled in the repository settings

**Comment by kubitron** [comment]
Can you tell me more about your environment?

Which version of this plugin are you using?  Also, can you run ./script/about from the Redmine root and show me the output?

Also, are there any errors in the log earlier than the one you showed me?

**Comment by pcaddict** [comment]
I am running version 0.4.3x of this plugin
Git version 1.7.9.2
Redmine version 1.3.1

Here is a list of installed gems: http://pastebin.com/3N7BAefv
Here is the output of ./script/about: http://pastebin.com/hxfNVBXf

The redmine production log (<redmine root>/log/production.log) does not show any other errors. Primarily entries noting access and page rendering. Here is some output from the production log when viewing the plugin properties:

Processing SettingsController#plugin (for 192.168.2.1 at 2012-02-27 20:55:42) [$
  Parameters: {"controller"=>"settings", "action"=>"plugin", "id"=>"redmine_git$
Rendering template within layouts/admin
Rendering settings/plugin
Our hook is already installed
Testing if git user("git") can sudo to web user("http")
Testing if web user("http") can sudo to git user("git")

The above tests are successful.

If you need any other information let me know.

**Comment by kubitron** [comment]
The problem with your output from ./script/about is that you didn't set your RAILS_ENV variable.

So, to be explicit:

For csh:

setenv RAILS_ENV production
./script/about

or bash:

export RAILS_ENV=production
./script/about

Etc.

**Comment by pcaddict** [comment]
Sorry about that. Correct output here: http://pastebin.com/iUmiiE1z

**Comment by kubitron** [comment]
Sorry.  I got busy!

Everything looked ok, except for the fact that you have a really old version of the gem program.  (It appears that pastebin expires content after a few days).

You might try:

gem update --system

Followed by

```
gem update
```

Also, was this a fresh install of Redmine 1.3.1? How about the plugin?  Did you remember to do a:

```
rake db:migrate_plugins RAILS_ENV=production
```

Just curious.

**Comment by kubitron** [comment]
p.s. I'm going to tentatively mark this as a configuration problem, but will keep working with you until we solve it...

**Comment by pcaddict** [comment]
I updated the gems as you suggested to no avail. The entire setup was clean. New OS install, new redmine, AND the plugin. I have setup another VM using essentially the same setup but with the latest stable ChiliProject and have everything working, including this plugin. As you said, likely a configuration issue on my part however I first noticed the problem with eric's project after upgrading redmine to 1.3.1. Prior to 1.3.1 everything was working as expected. Thanks for the help

**Comment by kubitron** [comment]
Hm.... Well, Eric's version doesn't work on Redmine 1.3.1 at all.  

Glad to hear that you have things working with ChiliProject.  Sorry that I wasn't more help.  Very weird.  I do know of others (besides myself) that have gotten things working with Redmine 1.3.1.  

Let me know if you have other problems.
