### ISSUE TITLE
repository not being created

### ISSUE THREAD

**Issue by mattsimpson** [kubitron/redmine_git_hosting#21]
Hello John,

I thought I'd post an issue in case you're able to help out with this problem I'm having.

The visible symptom to me is that when I create a new project, I'm not able to push to the repository:
system:testa userxyz$ git push -u origin master
W access for testa DENIED to userxyz
(Or there may be no repository at the given path. Did you spell it correctly?)
fatal: The remote end hung up unexpectedly

It looks to me like the repository isn't being created, here is the output when I run fetch_changes:
[root@projects redmine]# sudo -u apache RAILS_ENV=production rake gitolite:fetch_changes
fatal: Not a git repository: 'repositories/testa.git'
fatal: Not a git repository: 'repositories/testb.git'

Gitolite appears to be working, I can use it when it's cloned to my machine:
system:gitolite-admin userxyz$ git push
Counting objects: 7, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (4/4), 379 bytes, done.
Total 4 (delta 1), reused 0 (delta 0)
remote: Repository does not have "hooks.redmine_gitolite.key" set. Skipping hook.
remote: creating testxyz...
remote: Initialized empty Git repository in /home/git/repositories/testxyz.git/
To git@project.server:gitolite-admin.git
   5068595..3818e5d  master -> master

Also in case it's useful here is the about output:
[root@projects redmine]# ./script/about
/var/www/redmine-1.3/lib/redmine/scm/adapters/git_adapter.rb:26: warning: already initialized constant GIT_BIN
About your application's environment
Ruby version              1.8.7 (x86_64-linux)
RubyGems version          1.3.7
Rack version              1.1.3
Rails version             2.3.14
Active Record version     2.3.14
Active Resource version   2.3.14
Action Mailer version     2.3.14
Active Support version    2.3.14
Application root          /var/www/redmine-1.3
Environment               production
Database adapter          mysql
Database schema version   20111220055819

About your Redmine plugins
Redmine Git Hosting Plugin   0.4.3x

The only other possible relevant  piece of information I can think of is that the /tmp/redmine_git_hosting directory has nothing but the following file in it: /tmp/redmine_git_hosting/git/redmine_git_hosting_lock

Anyways, if you have any thoughts please let me know.

Best Regards,
Matt Simpson

**Comment by mattsimpson** [comment]
Oh my... it just took me erm 4 hours total to figure out that the problem was that the "Gitolite Server Domain" in the Redmine Git Hosting plugin configuration was resolving to a different server (despite the modification in the servers /etc/hosts file), so when the plugin was trying to clone the gitolite-admin repository, it was connecting to my current production project server not the new one I'm building.

Working well now. Thanks.

**Comment by kubitron** [comment]
Glad to hear it.  Sorry for not responding sooner! (Been busy).

I'm going to mark this as a configuration problem.
