### ISSUE TITLE
make tagged releases

### ISSUE THREAD

**Issue by anarcat** [kubitron/redmine_git_hosting#27]
Since this seems to become (or at least claims to become ;) the reference implementation for this feature, it seems to me it should start having proper release engineering. At the very least tags should be laid down on the tree (as opposed to just having the version number bumped in the README)...

This would also help packaging this plugin for Debian and other distributions.

**Comment by kubitron** [comment]
I'm not sure I'm claiming to become the reference implementation of this feature, but tagging seems like a reasonable request.  I'm assuming that you mean something like what is currently there (but which is out of date)?

**Comment by anarcat** [comment]
oh. funny, i didn't notice those tags. :P but I _did_ notice the 0.4.3 change in the README, and in my mind, this should be associated with a 0.4.3 release...

**Comment by kubitron** [comment]
So, that is the type of tag you want?  If so, I'll close out this issue and keep that in mind.

**Comment by anarcat** [comment]
yep thanks

**Comment by kubitron** [comment]
Not sure if you are still monitoring this bug, but I just tagged a 0.4.4x release.  Can you make sure that it still works well for you?  I think it should have everything you need (as well as other bug fixes).  It is what is at the head of master right now.

**Comment by kubitron** [comment]
Incidentally, I put a "release-notes" wiki page up.  Is this what you might want?
