### ISSUE TITLE
illegal mix of collations in fetch_changesets

### ISSUE THREAD

**Issue by anarcat** [kubitron/redmine_git_hosting#30]
Running fetch_changesets on our redmine instance yields:

```
Mysql::Error: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '=': SELECT `changesets`.`id` AS t0_r0, `changesets`.`repository_id` AS t0_r1, `changesets`.`revision` AS t0_r2, `changesets`.`committer` AS t0_r3, `changesets`.`committed_on` AS t0_r4, `changesets`.`comments` AS t0_r5, `changesets`.`commit_date` AS t0_r6, `changesets`.`scmid` AS t0_r7, `changesets`.`user_id` AS t0_r8, `users`.`id` AS t1_r0, `users`.`login` AS t1_r1, `users`.`hashed_password` AS t1_r2, `users`.`firstname` AS t1_r3, `users`.`lastname` AS t1_r4, `users`.`mail` AS t1_r5, `users`.`admin` AS t1_r6, `users`.`status` AS t1_r7, `users`.`last_login_on` AS t1_r8, `users`.`language` AS t1_r9, `users`.`auth_source_id` AS t1_r10, `users`.`created_on` AS t1_r11, `users`.`updated_on` AS t1_r12, `users`.`type` AS t1_r13, `users`.`identity_url` AS t1_r14, `users`.`mail_notification` AS t1_r15 FROM `changesets`  LEFT OUTER JOIN `users` ON `users`.id = `changesets`.user_id AND  (`users`.`type` = 'User' OR `users`.`type` = 'AnonymousUser' ) WHERE (`changesets`.repository_id = 290 AND (`changesets`.`committer` = 'Горлов Максим <sheridan@stavcom.ru>'))  ORDER BY changesets.committed_on DESC, changesets.id DESC LIMIT 1
```

**Comment by anarcat** [comment]
I can't reproduce this - my guess is that it happened as the plugin was caching a specific changeset.

**Comment by kubitron** [comment]
Does this mean that everything is working now?

**Comment by kubitron** [comment]
Also -- if you can properly run fetch_changesets, then you should be seeing RESYNC_ALL in the log after a fetch_changesets.  Right?

**Comment by anarcat** [comment]
well, fetch_changesets doesn't complain anymore, but I still have the problem in #29, and also a new one in #32, fairly serious.

**Comment by kubitron** [comment]
HM.... Googling this problem, it seems to be a problem that arises during the migration of old repos.  I'm not sure that it is directly a problem with this plugin.

Do you concur?  (I would like to close this one out, if possible).  As for #32, we will fix that as a separate issue...

**Comment by anarcat** [comment]
right, i honestly don't know. it seemed to me that it freaks out on bizarre charsets, but i can't reproduce so lets' close this.

**Comment by kubitron** [comment]
Ok.  Let me know if we need to reopen.
