### ISSUE TITLE
mirroring only works on the first mirror added

### ISSUE THREAD

**Issue by levelos** [kubitron/redmine_git_hosting#33]
If you add more than one mirror to a repository, the plugin only automatically pushes to the first one rather than all of the available mirrors. Manually triggering the push works for all of them.

**Comment by kubitron** [comment]
Ok.  Look in the log.  There should be one or more statements of the form:

```
Pushing changes to mirror [mirror_url]
```

In fact, there should be one for each mirror on every push.  Do you see anything like that?

**Comment by kubitron** [comment]
Ping!  Just curious if you are still working on this.

**Comment by kubitron** [comment]
Double ping....?

**Comment by levelos** [comment]
Hey @kubitron, sorry for the silence. I can't find anything along those lines in the production log. I can confirm, though, that the first mirror for a given repo is getting pushed but not any subsequent ones.

**Comment by kubitron** [comment]
Ok.  Sorry for the delay.  Try pulling things from my "testing2" branch (the "testing" branch has something else on it).  See if that takes care of the problem.  

Note that there should be better information in the log now...

**Comment by kubitron** [comment]
Ok.  @levelos, I moved this patch to my master branch.  When you get a chance, pull from master and make sure everything fixed...  (got too many testing branches, and I'm pretty sure I figured out what was causing your problem).

**Comment by levelos** [comment]
Thanks John, I'll give it a pull and let you know.

**Comment by kubitron** [comment]
Thanks.

**Comment by kubitron** [comment]
Ping!  Ping!  I just want to make sure that I fixed this...

**Comment by levelos** [comment]
Sorry John, at a conference this week. Will update next. Thx!

**Comment by kubitron** [comment]
OK.  (p.s. I edited your message on the issue page to remove your phone number -- a side effect of replying to comments with an email browser....).

**Comment by levelos** [comment]
Thanks!

**Comment by levelos** [comment]
BTW - Looks good with latest code base. Nice work, thanks!

**Comment by kubitron** [comment]
Ok.  Glad to hear it.

Will assume that this issue is _actually_ fixed.
