### ISSUE TITLE
french? translation missing in [project]/settings/repository and my/account pages

### ISSUE THREAD

**Issue by avoine** [kubitron/redmine_git_hosting#36]
Almost every labels shows something like: translation missing: fr, label_public_keys, translation missing: fr, field_git_daemon, etc

**Comment by kubitron** [comment]
Hm... There _is_ a translation file  fr.yml with all of those translations.  (Of course, they are all in English, but ...).

Do you have the same problem on the plugin settings page?

**Comment by avoine** [comment]
No, the plugin's configuration page is all in english.

**Comment by kubitron** [comment]
Ok. I cannot seem to reproduce this problem.  However, I would like to try an experiment.  

Can you pull from my 'testing' branch?  Restart redmine and see if the problem persists.  I have a theory.

**Comment by kubitron** [comment]
Hello?  Did I lose you? 

I want to see if the fix that is currently on my 'testing' branch fixes this problem...

**Comment by kubitron** [comment]
I would love to fix this, but I cannot reproduce.  I need for you to see if my attempt at a fix takes care of the missing "translations."  We can talk at another time about getting actual french translations in there. 

If I don't hear from you, I'll have to close this issue.

**Comment by kubitron** [comment]
Closing this bug.  I fixed the language tags on the translations -- which would possible cause this problem.  If you ever come back, you can pull from the master branch and see if everything works.
