### ISSUE TITLE
 lib/git_adapter_hooks.rb not finding directories

### ISSUE THREAD

**Issue by ghost** [kubitron/redmine_git_hosting#38]
Any interaction I had with git, I was having a difficult time.  The log produced something like below for one example.  When I would copy the commands and run them as my git user, no problems were reported.  When redmine would run it, it looked like the home directory was not being prepended to the relative git paths.

I simply set the home environment variable in init.rb and everything started working great.  I don't know why redmine would not have access to the home environment variable,  but setting it manually makes everything work.

I have this version of redmine checked out, which is 1.3.2+
c17e7e8

I have this version of kubitron redmine_git_hosting, from about 3/28/2012
fef6fda

I'm running Ubuntu Wheezy, testing.  All of the latest binary packages provided by the distribution as well as gems.  In other words the only source packages on my machine are redmine and it's plugins.

You can actually see where "~/" is getting translated to "" in the log below

_**> Command failed (return 2):  cat /var/www/redmine-dev/vendor/plugins/redmine_git_hosting/contrib/hooks/post-receive.redmine_gitolite.rb |  /var/www/redmine-dev/vendor/plugins/redmine_git_hosting/bin/run_as_git_user 'cat - > <b>~/.gitolite/hooks/common/post-receive</b>'
*_*>   sh: 1: cannot create <b>./.gitolite/hooks/common/post-receive</b>: Directory nonexistent

Log output:

``` ruby
Processing SettingsController#plugin (for 192.168.20.3 at 2012-04-01 04:49:55) [POST]
  Parameters: {"commit"=>"Apply", "action"=>"plugin", "authenticity_token"=>"9cmJr7NpgZwsFEDEkS0/KgL3bHdBIs/WaWfejbUFEXE=", "id"=>"redmine_git_hosting", "settings"=>{"httpServer"=>"dev.wda.local", "gitRedmineSubdir"=>"./", "gitRepositoryBasePath"=>"./repositories/", "gitoliteIdentityPublicKeyFile"=>"/var/www/redmine-dev/.ssh/gitolite_admin_id_rsa.pub", "gitLockWaitTime"=>"10", "gitHooksDebug"=>"false", "gitCacheMaxElements"=>"100", "gitDaemonDefault"=>"0", "gitCacheMaxTime"=>"-1", "gitServer"=>"dev.wda.local", "gitRecycleBasePath"=>"./recycle_bin/", "gitNotifyCIADefault"=>"1", "gitRepositoryHierarchy"=>"false", "httpServerSubdir"=>"./", "gitRecycleExpireTime"=>"24.0", "deleteGitRepositories"=>"false", "gitRepositoriesShowUrl"=>"true", "gitScriptDir"=>"./", "gitHooksAreAsynchronous"=>"true", "gitHttpDefault"=>"0", "gitoliteIdentityFile"=>"/var/www/redmine-dev/.ssh/gitolite_admin_id_rsa", "gitUser"=>"git", "gitTempDataDir"=>"/tmp/redmine_git_hosting/", "gitCacheMaxSize"=>"16", "allProjectsUseGit"=>"true"}, "controller"=>"settings"}
Executing RESYNC_ALL operation on gitolite configuration
Fetching changes from gitolite-admin repository to /tmp/redmine_git_hosting/git/gitolite-admin
Creating bin directory: /var/www/redmine-dev/vendor/plugins/redmine_git_hosting/bin/, Owner git
Setting up /var/www/redmine-dev/vendor/plugins/redmine_git_hosting/bin/
"post-receive" not handled by gitolite, installing it...
Installing "post-receive.redmine_gitolite.rb" from /var/www/redmine-dev/vendor/plugins/redmine_git_hosting/contrib/hooks/post-receive.redmine_gitolite.rb to ~/.gitolite/hooks/common/post-receive
***> Command failed (return 2):  cat /var/www/redmine-dev/vendor/plugins/redmine_git_hosting/contrib/hooks/post-receive.redmine_gitolite.rb |  /var/www/redmine-dev/vendor/plugins/redmine_git_hosting/bin/run_as_git_user 'cat - > ~/.gitolite/hooks/common/post-receive'
***>   sh: 1: cannot create ./.gitolite/hooks/common/post-receive: Directory nonexistent
***> install_hook(): Problems installing hook from /var/www/redmine-dev/vendor/plugins/redmine_git_hosting/contrib/hooks/post-receive.redmine_gitolite.rb to ~/.gitolite/hooks/common/post-receive.
"post-receive.redmine_gitolite installed
Running "gl-setup" on the gitolite install...
***> Command failed (return 1): /var/www/redmine-dev/vendor/plugins/redmine_git_hosting/bin/run_as_git_user gl-setup
***>   looks like first run -- I need a pubkey file
***> check_hooks_installed(): Problems installing hooks and initializing gitolite!
```

**Comment by kubitron** [comment]
This would appear to be a problem with your gitolite installation.  You need to fully install gitolite first. Use the instructions
for gitolite install that comes with that package.  At the top of the README file for this plugin, there is instruction about what to do with the public/private key pair that you have generated for interfacing between gitolite and Redmine.  I suggest 
that you follow the README very carefully.

**Comment by kubitron** [comment]
Sorry for closing this prematurely -- I have it marked as a configuration problem for now.  

How is it going?

**Comment by kubitron** [comment]
Are you still around?  If I don't hear from you, I'll assume that you fixed your problem...

**Comment by ghost** [comment]
John,

I am so very sorry for leaving you hanging on this; I got so busy this week
I became very disorganized.

You probably did fix the problem, but I will still check now that my week
is over

On Wed, Apr 4, 2012 at 6:56 PM, John Kubiatowicz <
reply@reply.github.com

**Comment by ghost** [comment]
The latest commits did not fix the issue.  However, I'm going with your previous concept of gitolite not being setup correctly - but I think it is prior to gitolite even being invoked so it must be something with my linux environment.  I'll try to track this external issue down and post my findings here.

**Comment by kubitron** [comment]
Did you ever run "gl-setup" manually with your key?  You need to do that to get gitolite setup.  If you notice, there is an error message above from gl-setup that says "looks like first run".  Just because gitolite is installed already by your installation does mean that it has been set up.  Get the instructions for gitolite installation off the web and notice that you need to:
1. create an adminstrative public/private key pair for connection between gitolite and redmine
2. execute gl-setup with the public key
3. put the two public/private pairs into:
   REDMINE_ROOT/.ssh/gitolite_admin_id_rsa.pub    and
   REDMINE_ROOT/.ssh/gitolite_admin_id_rsa

Make sure that these keys have the right permissions as indicated in the readme....

**Comment by kubitron** [comment]
Hello.  Please pull the latest version of the repository and look at the README (or look at it online).  I've put in explicit instructions on how to configure gitolite and generate the repository key.  In particular, there are new instructions in #1 and #4 of the "Step by step configuration instructions".  Perhaps this will help?

**Comment by kubitron** [comment]
Did you ever get this working??? If I don't hear from you soon, I'll close out this bug report.

**Comment by ghost** [comment]
Sorry this took so long, you can close this, I reinstalled a new installation of ubuntu, all of my dependencies, followed your guide and it worked.  I must have just destroyed my environment on the old VM because I just could not fix it.   Regardless, it was my environment so not a bug here.

**Comment by kubitron** [comment]
Great!  

Glad to hear it is working. Let me know if you have other problems.
