### ISSUE TITLE
Separate config files for managed repositories

### ISSUE THREAD

**Issue by rchady** [kubitron/redmine_git_hosting#44]
Would you please add support for having separate config files for managed repositories?  This simplifies the config management code and makes it much safer for working with repositories that are not managed by the plugin as there is no risk of conflict.

I implemented this in a much older version of this plugin, but enough changes have been made in this fork to make my changes incompatible.  The way I set it up was:

gitolite.conf -- manually managed, set up groups, the admin-repo, and then included other files
managed.conf -- fully managed by the plugin (included in to gitolite.conf)
internal.conf -- manually managed for other repositories that are not managed by the plugin (included in to gitolite.conf)

By breaking this apart, there is no risk of changes to a single file conflicting with other changes made for repositories not managed by the plugin.  It also removes the need for the code necessary for reading in gitolite.conf and trying to rewrite it each time.  This also makes it easier to use gitolite features such as being able to include other files as the gitolite.conf file does not get rewritten.

**Comment by kubitron** [comment]
OK.  Marked as a feature request.

**Comment by rchady** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

I'm hoping you are able to add this RSN so I can switch over to your plugin and stop being the only person supporting the custom plugin we run internally! ;)
- --Robert

On Apr 30, 2012, at 4:16 PM, John Kubiatowicz wrote:

> OK.  Marked as a feature request.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kubitron/redmine_git_hosting/issues/44#issuecomment-5427916

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.9 (Darwin)

iEYEARECAAYFAk+fB2AACgkQ8Eouv0ZUNqWf1gCfYbKya/c9rQjkwUwtKTh7TqVe
KIIAnRW5V/KhXU5W0m1CGM2ust+5vHNE
=1YR6
-----END PGP SIGNATURE-----

**Comment by nvx** [comment]
+1

**Comment by kubitron** [comment]
I hear you.  Sorry for the delay.  It is on my list of things RSN!  (got really busy).

**Comment by kubitron** [comment]
So, if I understand the requirement, all that is required is for the plugin to utilize a file of a different name which doesn't have to (shouldn't?) contain the administrative key?  This seems pretty simple and could be a quick fix.

**Comment by rchady** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

That is correct.  I implemented it as a configurable option for the "managed" config file.  What I ended up doing is setting up a gitolite.conf on the gitolite server that largely just included all the other config files, including the one managed by the plugin.  Has worked slick as can be.  In fact, since gitolite supports "reopening" a repo config, I actually have a 'managed.conf' that is managed by the plugin and a 'sitepen_managed.conf' that includes changes to things in managed.conf that I don't want to (or can't easily) do via the plugin, such as giving permission to system users that don't exist in ChiliProject, etc.
- --Robert

On Jul 17, 2012, at 6:46 PM, John Kubiatowicz wrote:

> So, if I understand the requirement, all that is required is for the plugin to utilize a file of a different name which doesn't have to (shouldn't?) contain the administrative key?  This seems pretty simple and could be a quick fix.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kubitron/redmine_git_hosting/issues/44#issuecomment-7052941

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.9 (Darwin)

iEYEARECAAYFAlAGGxsACgkQ8Eouv0ZUNqWpQgCg3bkdQHHf9wGba1S5SsEwnMGs
gSgAn1MCINCUE3zsZ/BXD+IYVB9PizcD
=LZuj
-----END PGP SIGNATURE-----

**Comment by kubitron** [comment]
Ok.  Well, you may have disappeared on me, but I have something for you to try on my testing branch.

Make sure to run:

```
rake db:migrate_plugins RAILS_ENV=production
```

There are two parameters to change on the settings page: the config file name and whether or not it should have the administrative key in it.  Let me know so that I can put this to my master branch.

**Comment by rchady** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

I have not disappeared on you, I've just been busy, busy, busy!  I responded to the last email so not sure if it got missed or what. 

Anyhow, based on what you say here and what i can see in the diff it looks like it'll do what I was talking about.
Will be a bit before I can test it out so feel free to push it to master.  I'll look at switching to it as soon as I can.
- --Robert
  On Jul 27, 2012, at 2:29 PM, John Kubiatowicz wrote:

> Ok.  Well, you may have disappeared on me, but I have something for you to try on my testing branch.
> 
> Make sure to run:
> 
>    rake db:migrate_plugins RAILS_ENV=production
> 
> There are two parameters to change on the settings page: the config file name and whether or not it should have the administrative key in it.  Let me know so that I can put this to my master branch.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kubitron/redmine_git_hosting/issues/44#issuecomment-7314029

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.9 (Darwin)

iEYEARECAAYFAlAS8VoACgkQ8Eouv0ZUNqVnwQCgv3VV0Yv2HEPm0xp+Cg8NH0UP
qBoAoNS0/Bcgp07vf6j/WXQjTr8IMnYx
=GSL9
-----END PGP SIGNATURE-----

**Comment by kubitron** [comment]
Not to worry -- I saw your previous email.  

I just would understand if you had switched to another solution.

Really sorry for the delay.

**Comment by rchady** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Nope, I just stayed with my own solution for now.  I WANT to move to yours though as you have some things in yours that I had slated to add to mine... hate to reinvent the wheel if I don't have to.

Thanks again for your work.
- --Robert

On Jul 27, 2012, at 2:57 PM, John Kubiatowicz wrote:

> Not to worry -- I saw your previous email.  
> 
> I just would understand if you had switched to another solution.
> 
> Really sorry for the delay.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/kubitron/redmine_git_hosting/issues/44#issuecomment-7314659

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.9 (Darwin)

iEYEARECAAYFAlAS8yEACgkQ8Eouv0ZUNqXvqgCgueEoE/M+Xauuae6WEfqsUSVo
8uEAn3yNRiSuiuenOhweaJrXG1ENfrsM
=hxyS
-----END PGP SIGNATURE-----

**Comment by kubitron** [comment]
Ok.  Let me know how it works.  After I verify that it isn't randomly breaking things under the standard usage mode, I may just push it to  master.  (I'll let you know if I do that, however).

**Comment by kubitron** [comment]
Any word on this functionality?  (I'd like to retire this issue if you think all is well).

**Comment by kubitron** [comment]
I've migrated this to master (and incremented the version to 0.4.6x).  I am assuming that you will tell me if there is a problem with this feature.  Please consider moving to the plugin on a regular basis.... (I'd like to have some verification that it is working for you at some point).

Please pull from master again.
