### ISSUE TITLE
[FEATURE] Post-Receive Hook Modification

### ISSUE THREAD

**Issue by macgngsta** [kubitron/redmine_git_hosting#45]
When attempting to change the post-receive hook i get the following error message:
"post-receive" is alreay present but it's not ours!

My guess from reading the issues in eric's and here is that this is by design, probably doing some md5 check to see if the hook is the correct one. 

I would like to keep the same hook, but at the end of the hook I want to fire off a call to Jenkins to kick off a build. I've searched a bunch of other places, is there some other way to do this? or is there some way to bypass this checksum check?

**Comment by kubitron** [comment]
Ok.  Try the latest master branch.  If you go to the settings page for a repository, it provides the ability to add a post-receive url which posts a json description of the change.
