### ISSUE TITLE
undefined method 'empty?' for nil:NilClass

### ISSUE THREAD

**Issue by ghost** [kubitron/redmine_git_hosting#46]
When I log in as administrator and update a user account to become administrator I get an Internal Server Error and the following error in the logs:

```
ActionView::TemplateError (undefined method `empty?' for nil:NilClass) on line #7 of vendor/plugins/redmine_git_hosting/app/views/gitolite_public_keys/_view.html.erb:
4: 
5: <fieldset class="public_key_view"><legend><%= l(:label_current_public_keys)%></legend>
6: <table class="list">
7:  <% if @gitolite_public_keys.empty? %>
8:      <tr><td><label><%=l(:label_no_public_keys)%></label></td></tr>
9:  <%end %>
10:     <% @gitolite_public_keys.each do |key| %>

    vendor/plugins/redmine_git_hosting/app/views/gitolite_public_keys/_view.html.erb:7
```

Is it possible to fix this?
Redmine: 1.4.1
Ruby: 1.9.3
redmine_git_hosting: latest clone (today)

**Comment by kubitron** [comment]
If you read the README, this plugin is not yet compatible with Redmine 1.4.xxx

**Comment by kubitron** [comment]
(I have not had time to make it compatible yet).

**Comment by ghost** [comment]
Ok, should have looked better at the README. When you get the time this is one issue I've found. It actually works pretty good overall in 1.4.1.

**Comment by kubitron** [comment]
Ok.  I have to figure out how to handle the multiple repos/project issue before I release 1.4.xx support.

**Comment by mback2k** [comment]
Any news on 1.4.xx support, yet? Are there specific areas where you may need help?

**Comment by kubitron** [comment]
Sigh.  Just time.  I may finally have time next week to catch up with the backlog of requests and issues.
