### ISSUE TITLE
Some issues with branches

### ISSUE THREAD

**Issue by paulloz** [kubitron/redmine_git_hosting#53]
Hi there ;)

I got a totally fresh install of Redmine 1.3.2 on a Debian Squeeze with your plugin. Everything seemed to work fine until I commited on my git repositorie on another branch than master.
I realized that commits on other branches does not appears in my _Activity_ tab. Even weirder, when I switch to the _repository_ tab, I can select that branch in the dropdown menu but all revisions hashs and comments are empty...
I don't understand what could be doing that...

If you want me to post some log or configuration, please ask.

Thanks.

**Comment by kubitron** [comment]
Was the Activity tab working properly with the master branch?  (I'm wondering if the commit hooks are working properly).  Have you tried executing a `fetch_changesets` operation?

**Comment by paulloz** [comment]
Yes, no problem when I'm using the master branch. And yes, I've run the fetch_changesets script :/

**Comment by kubitron** [comment]
Sorry that I dropped this.  Things got busy.

Anything new on this problem?  Seems like this might be a configuration problem...  When I ask about the "fetch_changests" script, I mean the one described in the README (making sure to run this as the same user as your web user!):

```
rake redmine_git_hosting:fetch_changesets RAILS_ENV=production
```

If you did this earlier, did you run it as your web user?  IF you don't this can mess up permissions on files in the /tmp directory.... (i.e. you could try deleting the /tmp/redmine_git_hosting directory and restarting everything to see if it helps).

Also, can you send me more information about your configuration?  Try running the "about" script in the Redmine root directory:

```
sh% RAILS_ENV=production ./script/about 
```

There should be a complete listing about your environment down there...

**Comment by kubitron** [comment]
I haven't heard from you in a while and will assume that you have fixed your problem.  I'll close it out, but reopen it if you still are having problems.  (i.e. please respond if you want more help).
