### ISSUE TITLE
repo removed when project is archived

### ISSUE THREAD

**Issue by simonsd** [kubitron/redmine_git_hosting#55]
When archiving a project in redmine, the next fetch_changesets deletes the repo.
I was hoping the repo could also be archived in a way.
Perhaps just check the db, see wether the project is in 'archived' state or something?

Wondering why it's actively being removed rather than just ignored though.
I'm assuming the plugin checks wether a project is 'active' or 'existent' and then determines to keep/remove it.
In this case could you include the archived projects in the 'active' list?

**Comment by kubitron** [comment]
Hm.... I suspect that there is no distinction there (i.e. that flag is not checked).  

Incidentally -- for the short term, if you are using my version of the plugin, at least the repo is placed into the recycle bin and can be recovered by reactivating the project.

I'll look into this.

**Comment by simonsd** [comment]
Yeah I figured as much.
Had a feeling this might not be accounted for, so I've got the repo backed up elsewhere.

Thanks for looking into it.

**Comment by kubitron** [comment]
Ok.  The reason for this behavior is pretty obvious (once I knew to look for it).  

Question: What should happen here?  Should the corresponding repos just stay in the repository (by far the easiest solution)?

**Comment by simonsd** [comment]
Yeah they should indeed just stay put, though maybe made unavailable?

**Comment by kubitron** [comment]
Does that mean taking them out of the git config file?

**Comment by simonsd** [comment]
Not necessarily, but it's an option yeah.
Another option would be to remove the list of keys allowed to access it.

**Comment by kubitron** [comment]
Ok.  Try the version at head of master.  Perhaps I'm a being risky by not putting this up on a testing branch, but I believe that it should do the right thing.

It will:
1. Remove redmine keys and the git-daemon key, leaving a dummy redmine key called "redmine_archived_project"
2. Delete any keys from the keydir that aren't being used by any projects any more.
3. Leave the repository where it is in the gitolite repo directory

You should be able to freely un-archive the project and get restored back to normal behavior.  Could you test?

**Comment by simonsd** [comment]
Thanks, I'll take a look tomorrow if I have the time.
Nice touch leaving the dummy key, definitely clears things up a bit for someone reading the gitolite config.

**Comment by simonsd** [comment]
Thanks for the fix, just tried it out and it works as expected.

archive project:
- repo stays put
- config has redmine_archived_project dummy key set

unarchive project:
- repo still in the same place
- config updated to have correct keys again
