### ISSUE TITLE
Broken pipe with git push over SmartHTTP 

### ISSUE THREAD

**Issue by iarspider** [kubitron/redmine_git_hosting#59]
Hi,

I'm setting up a Redmine+GIT site using your version of "redmine_git_hosting" plugin. I've used [this](http://www.redmine.org/projects/redmine/wiki/GitHub_clone_based_on_Debian_Squeeze_Gitolite_Git_Git-Daemon_MySQL_Nginx_and_Mongrel_Cluster) tutorial to set things up with mod_passenger, minus the parts about mongrel and ngoix.

The problem is, pushing always fails with SmartHTTP:

```
git push -u origin master
Password: 
Counting objects: 1417, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (819/819), done.
Writing objects: 100% (1417/1417), 1.49 MiB, done.
Total 1417 (delta 580), reused 1417 (delta 580)
error: RPC failed; result=22, HTTP code = 500
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
```

I get this error in apache log:

```
[ pid=13898 thr=140660873234240 file=ext/apache2/Hooks.cpp:862 time=2012-07-21 15:00:33.463 ]: Unexpected error in mod_passenger: An error occured while sending the request body to the request handler: Broken pipe (32)
  Backtrace:
     in 'virtual void Passenger::Session::sendBodyBlock(const char*, unsigned int)' (Session.h:198)
     in 'void Hooks::sendRequestBody(request_rec*, Passenger::SessionPtr&, boost::shared_ptr<Passenger::BufferedUpload>&)' (Hooks.cpp:1358)
     in 'int Hooks::handleRequest(request_rec*)' (Hooks.cpp:685)
```

and here is the contents of /opt/redmine/log/production.log:

```
Processing GitHttpController#index (for 192.168.56.101 at 2012-07-21 15:00:33) [GET]
  Parameters: {"action"=>"index", "path"=>["info", "refs"], "project_path"=>"hiasm5.git", "controller"=>"git_http", "prefix"=>"", "service"=>"git-receive-pack"}
Completed in 47ms (View: 1, DB: 3) | 200 OK [http://hiasm.local/redmine/hiasm5.git/info/refs?service=git-receive-pack]


Processing GitHttpController#index (for 192.168.56.101 at 2012-07-21 15:00:33) [POST]
  Parameters: {"action"=>"index", "path"=>["git-receive-pack"], "project_path"=>"hiasm5.git", "controller"=>"git_http", "prefix"=>""}
Filter chain halted as [:authenticate] rendered_or_redirected.
Completed in 9ms (View: 0, DB: 0) | 401 Unauthorized [http://hiasm.local/redmine/hiasm5.git/git-receive-pack]
```

I'm commit-ing as 'admin' (default user), and he has both "Manager" and "Developer" privileges.

**Comment by iarspider** [comment]
Old-style SSH push works fine

**Comment by kubitron** [comment]
I suspect that this is a problem with your apache configuration. There are tricks required to get the authentication to be passed on to Rails for requests over http.  I have some comment I about this in the Readme for redmine_git_hosting.  

(Look at the header for "Smart HTTP Functionality").  I don't use passenger, so I am not sure how this translates.  However, both mod_fcid and ngnix require configuration to get proper information passed though to Redmine (and hence to the plugin).

**Comment by iarspider** [comment]
Well, looks like such a fix is only needed for fcgi, and passenger is  supposedmto work out-of-the-box

**Comment by iarspider** [comment]
I have enabled more verbose logging in redmine, and I think it is clear that HTTP auth information is not passed to passenger:

```
Processing GitHttpController#index (for 192.168.56.101 at 2012-07-23 10:43:41) [GET]
  Parameters: {"path"=>["info", "refs"], "project_path"=>"hiasm5.git", "service"=>"git-receive-pack", "controller"=>"git_http", "prefix"=>"", "action"=>"index"}
  SQL (0.1ms)   SELECT max(`settings`.updated_on) AS max_updated_on FROM `settings`
  AnonymousUser Load (0.0ms)   SELECT * FROM `users` WHERE ( (`users`.`type` = 'AnonymousUser' ) ) LIMIT 1
  Setting Load (0.3ms)   SELECT * FROM `settings` WHERE (`settings`.`name` = 'default_language') LIMIT 1
  Project Load (0.0ms)   SELECT * FROM `projects` WHERE (`projects`.`identifier` = 'hiasm5') LIMIT 1
  Repository Load (0.0ms)   SELECT * FROM `repositories` WHERE (`repositories`.project_id = 1) LIMIT 1
  GitRepositoryExtra Load (0.0ms)   SELECT * FROM `git_repository_extras` WHERE (`git_repository_extras`.repository_id = 6) LIMIT 1
  Repository Load (0.0ms)   SELECT * FROM `repositories` WHERE (`repositories`.`id` = 6)
  CACHE (0.0ms)   SELECT * FROM `projects` WHERE (`projects`.`identifier` = 'hiasm5') LIMIT 1
Completed in 23ms (View: 0, DB: 1) | 200 OK [http://hiasm.local/redmine/hiasm5.git/info/refs?service=git-receive-pack]


Processing GitHttpController#index (for 192.168.56.101 at 2012-07-23 10:43:41) [POST]
  Parameters: {"path"=>["git-receive-pack"], "project_path"=>"hiasm5.git", "controller"=>"git_http", "prefix"=>"", "action"=>"index"}
  SQL (0.1ms)   SELECT max(`settings`.updated_on) AS max_updated_on FROM `settings`
  AnonymousUser Load (0.1ms)   SELECT * FROM `users` WHERE ( (`users`.`type` = 'AnonymousUser' ) ) LIMIT 1
  Project Load (0.1ms)   SELECT * FROM `projects` WHERE (`projects`.`identifier` = 'hiasm5') LIMIT 1
  Repository Load (0.2ms)   SELECT * FROM `repositories` WHERE (`repositories`.project_id = 1) LIMIT 1
  GitRepositoryExtra Load (0.1ms)   SELECT * FROM `git_repository_extras` WHERE (`git_repository_extras`.repository_id = 6) LIMIT 1
  Repository Load (0.1ms)   SELECT * FROM `repositories` WHERE (`repositories`.`id` = 6)
Filter chain halted as [:authenticate] rendered_or_redirected.
Completed in 10ms (View: 0, DB: 1) | 401 Unauthorized [http://hiasm.local/redmine/hiasm5.git/git-receive-pack]
```

**Comment by kubitron** [comment]
Um... It is Passenger that must pass auth information to Redmine.  At least for mod_fcid, the changes to the apache config file cause the login information to be passed along with the http information to Redmine...  

(Or, is that what you meant?)

**Comment by iarspider** [comment]
I'm not sure _where_ the information is lost, but the fact is that it _is_ lost... Also, there is 1 thing that bugs me: I've used Wireshark to capture exchange between the client and the server, and I see no signs of HTTP auth _at all_: http://pastebin.ca/2174077

**Comment by kubitron** [comment]
Hm... I remember being very frustrated getting the auth information to make it through from mod_fcgid.  Also, we managed to figure it out for ncgix as well.  Is there no mention of this on the web for passenger?

**Comment by kubitron** [comment]
Incidentally, don't know if this helps but, when things were not working for me with mod_fcgid, it was apache that was sending and processing the password query.  Of course, you want the password to be passed on to Redmine...

**Comment by iarspider** [comment]
Looks like I've found ~50% of the answer: one still needs Redmine.pm (and all those lines in apache config) to get password request.

**Comment by iarspider** [comment]
Now I'm stuck again. What I want is to have redmine, "big" forum and git repositories on one host. Here is my apache config: http://pastebin.ca/2174309
Push still fails, but with a different error message:

```
remote: Empty compile time value given to use lib at hooks/update line 6
remote: Use of uninitialized value in require at hooks/update line 7.
remote: Can't locate Gitolite/Hooks/Update.pm in @INC (@INC contains:  /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at hooks/update line 7.
remote: BEGIN failed--compilation aborted at hooks/update line 7.
remote: error: hook declined to update refs/heads/master
```

Google tells me that this is because I somehow bypass gitolite. So, the question is - what am I missing in the config?

**Comment by kubitron** [comment]
The problem with this approach is that you are doing the password authentication in Apache.  You don't want to do that.  You want to pass the passwords on through to Redmine.  It is Redmine that should say  "ok" and processes the http request.

**Comment by kubitron** [comment]
Here is my Apache config:

```
<Location /redmine>
    RewriteEngine On
    # Let apache handle purely static files like images by itself.
    RewriteCond %{REQUEST_FILENAME} !-f

    # Send Everything else to Typo
    RewriteRule ^(.*)$ dispatch.fcgi [E=X-HTTP_AUTHORIZATION:%{HTTP:Authorization},QSA,L]
</Location>
```

Note that it is the options with X-HTTP_AUTHORIZATION that make this configuration work and pass passwords through.

**Comment by iarspider** [comment]
Well, since this plugin didn't work for me, I've switched to plan grack. This issue can be closed now.

**Comment by kubitron** [comment]
Before you totally give up, can you try something like this? (Just pass through the authorization):

```
<Location /redmine>     # Or whatever your location is
    RewriteEngine On

    # Pass authorization information to rails
    RewriteRule .* - [E=X-HTTP_AUTHORIZATION:${HTTP:Authorization},QSA,L]
</Location>
```

Not entirely sure about either the QSA or L.  Try with and without the L.  You can probably put this in your virtual hosts entry as well.

**Comment by leelyle** [comment]
Hi.
I have the exactly same problem after upgraded my system, including apache, gitolite...
it will success if I commit a fewer changes in git then push. 
if i make more changes, push will fail.
And I have tried the config above, still the same error.

**Comment by kubitron** [comment]
Can you tell me what your configuration is?

This does work with fcgi.  Are you using passenger?

**Comment by leelyle** [comment]
Yes, I was using passenger.
the configuration:
<Directory /var/www/redmine>
        RailsBaseURI /redmine
        PassengerResolveSymlinksInDocumentRoot on
</Directory>

maybe there is a bug in new version of passenger
I switched to fcgi, which is working fine.
Thanks for the suggestion

**Comment by kubitron** [comment]
Glad to hear that it works for you.

I really wish that someone would figure out the passenger problem (I don't use passenger myself).
