### ISSUE TITLE
repos are not moved on project move

### ISSUE THREAD

**Issue by simonsd** [kubitron/redmine_git_hosting#6]
I moved one of my projects containing a repo earlier; and neither the gitolite config nor the repos itself were updated to reflect that change.
The repos itself are still at the old path, same for the gitolite config.
I presume the plugin isn't hooked in to the project moving action or something like that?
Is this expected behavior, a freak bug or just not implemented yet?
Not sure if you need more info, just ask if I forgot anything.

**Comment by kubitron** [comment]
Oops.  Now _that_ is not expected at all.

Can you give me more information?  Can you show me the log message associated with the move?  Also, post the conf file for me to look at and tell me which project....

**Comment by kubitron** [comment]
Tell me what you moved.  Did you move to a different parent or something else?

**Comment by kubitron** [comment]
Here is what should happen when you change the parent of a project:

<pre>
Processing ProjectsController#update (for 128.32.168.227 at 2012-01-27 15:12:55) [PUT]
  Parameters: {"commit"=>"Save", "action"=>"update", "_method"=>"put", "authenticity_token"=>"f46GI0+NJ8CamR1thpUE5+D9M3QttN6QUoImfct3vZM=", "id"=>"this-is-a-test", "project"=>{"name"=>"Testing", "tracker_ids"=>["1", "2", "3", ""], "homepage"=>"", "parent_id"=>"5", "is_public"=>"0", "description"=>""}, "controller"=>"projects"}
Redirected to https://tessellation.cs.berkeley.edu/test-site/redmine/projects/this-is-a-test/settings
Fetching changes from gitolite-admin repository to /tmp/redmine_git_hosting/git-tess/gitolite-admin
Creating MD5 digests for Redmine Git Hosting hook
Digest for post-receive.redmine_gitolite.rb: 08e9b3cf99fa6285331ccdcef8b9a0d3
Our hook is already installed
Moving entry 'this-is-a-test' to 'tess-kernel/this-is-a-test' in gitolite.conf.
  Moving gitolite repository from 'this-is-a-test.git' to 'tess-kernel/this-is-a-test.git'
Committing changes to gitolite-admin repository
Completed in 1978ms (DB: 44) | 302 Found [https://tessellation.cs.berkeley.edu/test-site/redmine/projects/this-is-a-test]
</pre>


Did that not happen?  See if you can find the #update action in the log.  What does it look like?

**Comment by simonsd** [comment]
Yep, that's exactly what I did.
The parent_id is now empty, as opposed to before where it had a single project listed as its parent.

**Comment by simonsd** [comment]
Here is the entire log entry.
Moving the project went just fine, the repo however stayed put.

<pre>
Processing ProjectsController#update (for 10.0.2.2 at 2012-01-27 22:42:26) [PUT]
  Parameters: {"commit"=>"Save", "action"=>"update", "id"=>"puppet", "controller"=>"projects", "authenticity_token"=>"XxFMSUMK+E9cYMiCs+u6UElkK25oIF6v7U5mlSpkdZk=", "project"=>{"tracker_ids"=>["1", "2", "3", "4", ""], "is_public"=>"0", "parent_id"=>"", "description"=>"everything regarding puppet", "homepage"=>"", "name"=>"Puppet"}, "_method"=>"put"}
Redirected to http://apuri:8007/projects/puppet/settings
Completed in 60ms (DB: 25) | 302 Found [http://apuri/projects/puppet]
</pre>


Sorry for the slow reaction times, my terminal isn't very copy/paste friendly so it takes a while to get all the information out.
Besides that I'm just slow :)
But thanks a lot for helping me, you've done a great job so far.

**Comment by kubitron** [comment]
Weird.  Tell me again what version of Redmine you are using?  What if you move the project back?  Does the plugin get invoked then?

**Comment by kubitron** [comment]
Also -- try a move that doesn't seem to have worked, then execute a "fetch_changesets" operation and see if it moves then... (Also -- sorry to give you trouble, but try to show me the action with the fetch_changesets operation as well).

**Comment by kubitron** [comment]
BTW.  I'm wondering if things might have gotten out of sync when you were getting errors with the mirror.  By executing fetch_changesets, you might get everything resynced properly and then it might work...

**Comment by simonsd** [comment]
I'm on redmine 1.2.1 with the private messages patch applied.
Everything else is standard.
I just tried moving another project and this time it worked.
Moving it back also works as expected.
You might be right though, I did run fetch_changesets manually earlier,
and I also installed a few new plugins in between, so I ran some db migrations as well.

Still a bit confused as to what exactly updates the source tree in the redmine gui.
Should fetch_changesets do this? I've noticed that it doesn't get updated for a while,
no matter what I try. Then after a while it is updated by itself.

**Comment by kubitron** [comment]
What do you mean by "updates the source tree"?

**Comment by simonsd** [comment]
as in the repository page where you can view the source tree, or the 'revisions'.
These are correctly showing the first time I push to the repo,
but any subsequent push doesn't show.
When manually pushing to the mirror at that point the external repo is updated correctly though.

I've tried running the fetch_changesets, fetch_changes, update_repositories rake tasks from command line as well as the /sys/fetch_changesets?key=xxxxxx stuff from my browser.
None of those make a difference.
Should the browser method show an empty page upon succeeding? That's what I always get anyways ..

**Comment by kubitron** [comment]
Simple question first: yes, the browser should show an empty page when you fetch_changesets.

As for the updates, look at the log.  When you update, there should be an entry in the log with an "action"=>"post_receive".  This is showing that the  hook is working correctly.  Also, when you look at activity, you should see your updates mentioned quickly.  

If you don't see such updates, there may be a problem with the "hook".  There is new code that I added that tries to fix the hook when you execute fetch_changesets (if it is broken).  Note that the hook is written in ruby and runs as the git user.

There is a redmine_git_hosting setting for whether the update hook is asynchronous or not -- you could try changing it to see if there is a difference in the timing...

**Comment by simonsd** [comment]
Ok I'm not seeing any post-receive actions.
It appears the post-receive hook isn't running at all.
Does the hook use the httpServer param in any way?
When running a git push towards the repo, I get some html being dumped to my terminal,
which is from no-ip (dynamic dns provider).
Since my external access goes through no-ip, perhaps they're doing something wrong?

**Comment by simonsd** [comment]
myeah, no-ip seems to be the evildoer.
However since the httpServer param accepts an optional port I'm able to route the traffic through dyndns instead,
which does the trick.
Now the post-receive hook is running as expected and the changesets, source tree, activity stuff is all propagating nicely.
Thank you for another job well done.

I think I'll treat the not moving repos as a freak accident, and see if I can figure it out next time.
Since I'm unable to reproduce the issue at this time, I'm assuming I jumped the gun.
Sorry for wasting  your time like this.

**Comment by kubitron** [comment]
Resolution of this problem: repos may have been out of sync.  Good idea to execute fetch_changesets regularly -- will fix any errors that creep in!

Let's watch for other examples of this weirdness during normal operation, however.  Let me know if it appears again.

**Comment by simonsd** [comment]
Sounds about right.
We took this into production at my company yesterday, so that'll be quite the testing platform.
The errors I reported were on my own infra though, luckily.

If I may suggest something: is there any way to make the browser initiated fetch_changesets a bit more verbose?
As in showing the output of the commands, or just 'success' or 'failure'?
Right now it's a bit hard to guess, and if you're at a critical moment where you assume everything went ok while it didn't,
it might actually be disasterous.
Imho this makes it unusable for regular use. I'll be running it from the command line for now.

**Comment by kubitron** [comment]
Actually, you should run fetch_changesets from a cron job.  Do it every 15 minutes or so... It will correct any problems in the gitolite interface that crop up (including fixing problems with repo directories).

As for more info, that is not really the Redmine way, since it is intended to be run from cron/scripts...  Any errors go into the log.

**Comment by simonsd** [comment]
Point taken.
I suppose I misunderstood the intended use of the browser driven fetch_changesets.
My bad, thanks for pointing that out :)
