### ISSUE TITLE
Processing UsersController#edit failure

### ISSUE THREAD

**Issue by kinyobi** [kubitron/redmine_git_hosting#62]
When selecting a user who was just created or who has already logged in and configured their ssh public keys I am getting the following error in my production.log as well as on screen:

```
Processing UsersController#edit (for 127.0.0.1 at 2012-08-26 10:25:38) [GET]
  Parameters: {"action"=>"edit", "id"=>"4", "controller"=>"users"}

ActiveRecord::StatementInvalid (SQLite3::SQLException: near "&": syntax error: SELECT * FROM "gitolite_public_keys" WHERE (active=1 && key_type=0) AND ("gitolite_public_keys".user_id = 4)  ORDER BY title ASC, created_at ASC):


Rendering rescues/layout (internal_server_error)
```

Let me know if there is something more I can give. 

Running redmine 1.3.3 + redmine_git_hosting pulled as of last night.

**Comment by kubitron** [comment]
Did you remember to run "rake db:migrate_plugins"?

Also, can you run "./script/about" and show me the output?  (You need to set the RAILS_ENV environment variable first).  Thus, under csh from the redmine root, do:

```
prompt% setenv RAILS_ENV production
prompt% ./script/about
```

Under bash, do:

```
prompt% export RAILS_ENV=production
prompt% ./script/about
```

Please report the output.

**Comment by kubitron** [comment]
Actually -- I accidentally used non-standard SQL for something and didn't catch it because I'm using mysql.

Try pulling from master again and see if the problem goes away.

Sorry.

**Comment by kinyobi** [comment]
Pulled from master and everything is fine now.

Thanks for the quick fix!

**Comment by kubitron** [comment]
Great!

Sorry for the problem.  Since you are grabbing the 0.4.6x version, make sure to check out the new options on the Repository settings page (i.e. DeploymentCredentials, Post-Receive URLs, and updated Mirrors).

There were a bunch of changes in this release, so please let me know if there are any other problems.
