### ISSUE TITLE
Errors while uninstalling plugin

### ISSUE THREAD

**Issue by saric** [kubitron/redmine_git_hosting#68]
My Redmine config:
- Redmine 1.4.4.stable
- Rails 2.3.14
- ruby 1.8.7
- Phusion Passenger 3.0.12
- nginx 1.3.5
- mysql 5.1
- Scientific Linux 6.1
- Redmine is installed in subURI.

Testing was done on clean Redmine installation (fresh install without any other plugins) and using redmine_git_hosting from testing branch.

Plugin uninstallation procedure gives an error:

`$ rake db:migrate:plugin NAME=redmine_git_hosting VERSION=0 RAILS_ENV=production
Mysql::Error: Can't DROP 'notified_cia'; check that column/key exists: ALTER TABLE `changesets` DROP `notified_cia``

**Comment by kubitron** [comment]
Hmmm... Didn't know if that code has ever been tested (that would be a migration before I took over the plugin).  Did you successfully run the "db:migrate_plugins" first?

**Comment by saric** [comment]
Yes, I did.

**Comment by kubitron** [comment]
Ok. Is this a high-priority issue right now?  I may need to save my hacking cycles to getting the 1.4 release in good shape.  I will look at it, however.... (Is that the right syntax to remove all migrations for a plugin?  I guess I always wondered how to undo a migrate_plugins).

**Comment by saric** [comment]
No, this is not  high-priority issue right now. We all want to install
plugin and use it, and not to uninstall it :-)
Yes, that's correct command to downgrade redmine database, according to
Redmine documentation:
http://www.redmine.org/projects/redmine/wiki/Plugins

 Keep up the good work!

**Comment by kubitron** [comment]
Say @saric have you been able to use the testing branch with Redmine1.4 successfully?  I'm hoping to push it out to the master branch soon...

**Comment by saric** [comment]
I won't be able to test it until next week.

**Comment by kubitron** [comment]
Ah.  I thought you were using it already, since you were reporting bugs.... (I haven't debugged the inability to uninstall yet).

**Comment by kubitron** [comment]
Hello again.

So, I believe that this problem with uninstallation should be fixed.  Can you try the head of master?

**Comment by kubitron** [comment]
Just checking in -- I'd like to close out this bug... I _believe_ that uninstallation is now working.

**Comment by saric** [comment]
Hello John. 
Sorry, I wasn't able to test it earlier. Uninstallation works now as expected.
Thank you for your work.

**Comment by kubitron** [comment]
Great!  Let me know if the plugin is still working for you (head of master now includes some patches to make < Redmine 1.4 work again (my bad) -- hopefully didn't mess up Redmine 1.4 support).

Thanks for closing out this bug.

**Comment by saric** [comment]
Yes, it works with code from master branch.

**Comment by kubitron** [comment]
Good.  I am hoping to actually freeze the 0.5.0x release.  Thanks again for the debugging.  I don't normally like to release code in a beta (alpha?) state, but the bugs got shaken out a lot faster than they would have otherwise.
