### ISSUE TITLE
Several errors on repository creation

### ISSUE THREAD

**Issue by frasten** [kubitron/redmine_git_hosting#70]
I'm using the latest commit (0525cdc2fe) from the `testing` branch, and I'm running Redmine 1.4.4.

If I go under `http://REDMINE_URL/projects/MYPROJECT/repositories/new`, and I create a new repository, it won't be created by gitolite, and in the logs I see some errors:

```
ActionController::RoutingError (No route matches "/plugin_assets/redmine_git_hosting/javascripts/modalbox/lib/builder.js" with {:method=>:get}):
```

```
  Letting gitolite create empty repository: 'repositories/hydralisk.git'
***> undefined method `is_public' for #<Repository::Git:0x7f05555c35d0>
```

(full log is available [here](http://pastie.org/4809506))

Thank you.

**Comment by kubitron** [comment]
Oops.  This is my bug.

Try pulling the next commit off the testing branch.  Thank you for your patience...  (This branch represents a lot of changes).

**Comment by kubitron** [comment]
(going to close this bug -- reopen if still a problem).

**Comment by frasten** [comment]
Thank you, the repository now gets created correctly.

**Comment by kubitron** [comment]
Hm.... I'm actually slightly surprised... You better pull the next patch as well.
