### ISSUE TITLE
Possible configuration issue

### ISSUE THREAD

**Issue by frasten** [kubitron/redmine_git_hosting#71]
Hi, I'm really sorry if this issue is only a misconfiguration on my side, but I've been struggling with this for some days.

My setup:
- redmine_git_hosting commit 0525cdc2fe from branch testing
- Redmine 1.4.4
- Redmine URL: http://hydraulics-prod.ing.unibs.it/redmine/
- Redmine ROOT path: /home/redmine/redmine/
- Gitolite v2.3.1
- Gitolite user: git
- /etc/passwd: `git:x:496:494:Git Administrator:/opt/git:/bin/bash` => home: /opt/git/
- Repositories path: /opt/git/repositories/

I have a project named `hydralisk`, its repository is located at `/opt/git/repositories/hydralisk.git`, and gitolite works ok with it. Also redmine_git_hosting sets correctly gitolite permissions.

Unfortunately, clicking on the Repository link in the project, Redmine says that the repository is empty, and it shows the instructions.
However, I've managed to temporarily fix it by manually editing the `root_url` field in the DB, in the `repositories` table. It was set to `repositories/hydralisk.git`, and I've tried to set the absolute path: `/opt/git/repositories/hydralisk.git`. In this case Redmine sees correctly the repository, with all the commits loaded ok.
Unfortunately this option is rewritten when I change page, and obviously this is just a workaround.
I've also tried to understand _where_ is the relative path to, and it seems to be the Redmine ROOT (`/home/redmine/redmine`).
The only changes I've done to `init.rb` are:

```
       'httpServer' => 'hydraulics-prod.ing.unibs.it',
       'httpServerSubdir' => 'redmine/',
       'gitServer' => 'hydraulics-prod.ing.unibs.it',
```

Thank you, I love this plugin.

**Comment by kubitron** [comment]
No -- the "empty repository" information is because there are no commits there yet.  The repository is constructed (and in the repository), but it is empty.  You just need to follow the instructions.  Do not try to make the repository URL absolute -- it is relative to the git user home directory.

However--there were a couple of bugs on that version of the plugin -- please pull the latest commit.

**Comment by frasten** [comment]
Well, actually the repository is _not_ empty. I can push my commits with gitolite, and the commits are stored inside that repository (`/opt/git/repositories/hydralisk.git`). I've verified by cloning that directory locally.
Also, I've read in the readme file that the path should be relative to the git user home directory (in my case, it should be /opt/git); however, I've verified that in my case it is relative to Redmine root:
- `../../../opt/git/repositories/hydralisk.git` works;
- `vendor/../../../../opt/git/repositories/hydralisk.git` works.
- `../../opt/git/repositories/hydralisk.git` doesn't work.
  So something seems broken... I've done all these tests with commit b445672b92d8.

**Comment by kubitron** [comment]
?  If /opt/git is your home directory, then /opt/git/repositories/hydralisk.git is exactly the right place.  I'm not sure I understand your question.  Is this not what is happening?

The repositories option in the settings page should be just "repositories/".  This will mean that all repos at the top level will end up in ~gituser/repositories/.  Is this not what is happening?  Note that repositories _have_ to be under the git user's home directory.

**Comment by frasten** [comment]
Sure. `/opt/git/repositories/hydralisk.git` is the right place, and it is a bare repository (but not empty, I have already pushed my previous commits to it, and it works just fine).
The repositories option is set to "./repositories/".
_But_ Redmine says it is empty, _until_ I manually edit the `root_url` field in the DB, in the `repositories` table.
So I don't quite understand what's going on...
If I run:
`sudo -u apache rake redmine_git_hosting:fetch_changesets RAILS_ENV=production`
I get:

```
[Performing manual fetch_changesets operation...
fatal: Not a git repository: 'repositories/hydralisk.git'
DONE.]
```

But the directory exists, and it is a valid git repository:

```
ls -lha /opt/git/repositories/hydralisk.git
totale 40K
drwxr-x---    7 git git 4,0K 26 set 20:44 .
drwxr-x---.   8 git git 4,0K 26 set 19:47 ..
drwxr-xr-x    2 git git 4,0K 28 gen  2011 branches
-rw-rw-r--    1 git git  268 26 set 20:44 config
-rw-r--r--    1 git git   23 28 gen  2011 HEAD
drwxr-xr-x    2 git git 4,0K 26 set 15:36 hooks
drwxr-xr-x    2 git git 4,0K 18 nov  2011 info
drwxr-xr-x  215 git git 4,0K 26 set 14:11 objects
-rw-r--r--    1 git git  266 18 nov  2011 packed-refs
drwxr-xr-x    4 git git 4,0K 28 gen  2011 refs
```

And the git user home directory is set correctly:

```
# cd ~git && pwd
/opt/git
```

Any other test I can make to debug this issue? Thank you! :-)

**Comment by kubitron** [comment]
Did you try running a "fetch_changesets" operation after you push your commits?  Also, you could try turning off the cache (look at the settings page).  If the latter works, I suspect that there is a problem with the gitolite update hook.

**Comment by kubitron** [comment]
(Also -- is this a "secondary" repository, namely one that has a non-empty identifier)?

**Comment by frasten** [comment]
Yes, I tried running fetch_changesets _after_ pushing commits. Unfortunately the error is the one above ("fatal: Not a git repository: 'repositories/hydralisk.git'").
Now I've tried turning off the cache, but still no luck ("Not a git repository").
This isn't a secondary repository: the identifier is an empty string.

**Comment by kubitron** [comment]
Tell me again where the repo shows up?  What is the value of the root_url?  Also, could you send me the log messages (in log/production.log) around where the repo is constructed?  Also, when you try to do the fetch_changesets?

Thanks.

**Comment by frasten** [comment]
Now the value of root_url is set to "repositories/hydralisk.git".
Now, repo creation, step by step:
- I go to http://hydraulics-prod.ing.unibs.it/redmine/projects/hydralisk/settings/repositories
- I create a new repository, hit create (leaving the identifier empty)
- Everything ok now: the repository is created:

```
# ls -lha /opt/git/repositories
[...]
drwxr-xr-x  7 git git 4096 26 set 21:48 hydralisk.git
[...]
```
- I click on Repository, it says it is empty, correct.
- From my PC, I push my commits:

```
$ git push --all origin
Counting objects: 2404, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (1251/1251), done.
Writing objects: 100% (2404/2404), 12.32 MiB | 34 KiB/s, done.
Total 2404 (delta 1388), reused 1930 (delta 1096)
To git@hydraulics-prod.ing.unibs.it:hydralisk.git
  [new branch]      master -> master
  [new branch]      devel -> devel
....
```
- Let's test this repository:

```
git clone /opt/git/repositories/hydralisk.git /tmp/hydralisk
ls -lha /tmp/hydralisk
```

shows all my files.
Everything ok.
In the logs I see "GitoliteHooksController#post_receive", it seems to have already notified Redmine.
- I go into Redmine, click on Repository. Sbam: "Repository is empty. "
- Let's try to manually fetch the commits:

```
root@hydraulics-prod:/home/redmine/redmine# sudo -u apache rake redmine_git_hosting:fetch_changesets RAILS_ENV=production
[Performing manual fetch_changesets operation...
fatal: Not a git repository: 'repositories/hydralisk.git'
DONE.]
```
- I retry in Redmine, under Repository: no joy, still "Repository is empty."

:-(

The whole log is here: http://pastie.org/4811071
Thank you!!! :-)

**Comment by frasten** [comment]
Also, I now tried to read the database values for this repository:
- `url` and `root_url` are set to "repositories/hydralisk.git".
- `identifier` is an empty string.
  Now I try to set `root_url` to "/opt/git/repositories/hydralisk.git". Hit on Repository in Redmine and magically the repository is here. The log related to this last operation is:

```
Processing RepositoriesController#show (for 93.33.230.161 at 2012-09-26 22:20:42) [GET]
  Parameters: {"action"=>"show", "id"=>"hydralisk", "controller"=>"repositories"}
Fetching changes from gitolite-admin repository to /tmp/redmine_git_hosting/git/gitolite-admin
Our hook is already installed
Rendering template within layouts/base
Rendering repositories/show
Completed in 8664ms (View: 460, DB: 972) | 200 OK [http://hydraulics-prod.ing.unibs.it/redmine/projects/hydralisk/repository]
```
- Now, if I read again the `root_url` field, it has been automatically reverted again to "repositories/hydralisk.git". If I refresh the Repository page in Redmine, it says again that the repository is empty.

**Comment by kubitron** [comment]
Note that the root_url is supposed to be "repositories/hydralisk.git".  The fact that it reverts is a feature.

I have a theory - is it possible that you have invoked the web server in some way that sets the $HOME variable?  When the repository is accessed, it is accessed via shell scripts that use sudo.  If the $HOME variable is set, then sudo won't execute from the home directory of the git user, and the access path will be broken.

**Comment by frasten** [comment]
Hmm, this theory makes sense. I'm using Passenger on Apache, and [this](http://pastie.org/4845823) is the relevant part in `httpd.conf`. But how to verify it?
I've conducted another test, setting log level to `debug`. [This](http://pastie.org/4845458) is the log when clicking on _Repository_ under Redmine.
Isn't it supposed to use `sudo` and the scripts in the `bin/` directory?
I've tried to replace `cd ~` with `cd ~git` (ignoring the `$HOME` variable) inside these scripts, but this doesn't affect the results.
Note that this plugin used to work some time before introducing those scripts in `bin/`.

Thank you again!

**Comment by kubitron** [comment]
Well, it is the "sudo" command that is having problems in bin/run_as_git_user

You could try replacing:

```
exec("sudo -u git -i eval \"$command\"");
```

with

```
exec("sudo -u git -i eval \"cd ~git; $command\"");
```

See if that helps...

**Comment by frasten** [comment]
I think that those scripts don't get called when I click on Repository under my project:
I added:

```
touch /tmp/AAAA
```

at the beginning of `run_git_as_git_user`, and:

```
exec("touch /tmp/BBBB");
```

at the beginning of `run_as_git_user`.
I clicked on Repository, but no file is created under `/tmp` (it is 777 and I don't use selinux).
I have disabled the cache in the redmine_git_hosting options.
So may it be Redmine itself (and not redmine_git_hosting) who is trying to read the repository directory?

**Comment by kubitron** [comment]
Hmmm..... that is interesting.  It says to me that the git_adapter_patch is not running properly.

Can you try pulling the one extra commit from the 'debugging' branch?  I added debugging in the crucial file.  If the right things are happening, you should get lots of debugging like:

```
About to execute CachedShellRedirector(''/source/tessellation/test-site/redmine/vendor/plugins/redmine_git_hosting/bin/run_git_as_git_user' '--git-dir' 'repositories/tess-paper/asplos-2013.git' 'ls-tree' '-l' 'master:'','asplos-2013')
About to execute CachedShellRedirector(''/source/tessellation/test-site/redmine/vendor/plugins/redmine_git_hosting/bin/run_git_as_git_user' '--git-dir' 'repositories/tess-paper/asplos-2013.git' 'log' '--no-color' '--encoding=UTF-8' '--date=iso' '--pretty=fuller' '--no-merges' '-n' '1' 'master' '--' 'Makefile'','asplos-2013')
About to execute CachedShellRedirector(''/source/tessellation/test-site/redmine/vendor/plugins/redmine_git_hostingbin/run_git_as_git_user' '--git-dir' 'repositories/tess-paper/asplos-2013.git' 'log' '--no-color' '--encoding=UTF-8' '--date=iso' '--pretty=fuller' '--no-merges' '-n' '1' 'master' '--' 'abstract.tex'','asplos-2013')
About to execute CachedShellRedirector(''/source/tessellation/test-site/redmine/vendor/plugins/redmine_git_hosting/bin/run_git_as_git_user' '--git-dir' 'repositories/tess-paper/asplos-2013.git' 'log' '--no-color' '--encoding=UTF-8' '--da
te=iso' '--pretty=fuller' '--no-merges' '-n' '1' 'master' '--' 'acm_proc_article-sp.cls'','asplos-2013')
```

On the other hand, if things don't work, you will see an error something like:

```
***> Failure to map git_cmd!
```

**Comment by frasten** [comment]
Err... I tried pulling the debugging branch (commit d1639df), but... I don't see any of those two messages!
The full log is here: http://pastie.org/4857491
So `lib/git_hosting/patches/git_adapter_patch.rb` isn't working at all, is it!?
I've tried adding:

``` ruby
Rails.logger.error "TEST"
```

at the end of that file, and it appears in the logs, so the file seems to be loaded.

Note: I double-checked that the new commit was applied, and it is indeed: I can see the new two log lines.

**Comment by kubitron** [comment]
This is now officially weird.

The only thing I can think of is that the git_adapter.rb gets reloaded after the git_adapter_patch happens.  Do you have any plugins?

**Comment by kubitron** [comment]
(I meant plugins other than redmine_git_hosting)

**Comment by frasten** [comment]
I've already uninstalled all the other plugins some hours ago. :-/

**Comment by kubitron** [comment]
Just to make sure that they were uninstalled, however, could you show me a ./script/about output?

```
sh% cd /home/redmine/redmine
sh% export RAILS_ENV=production
sh% ./script/about
```

**Comment by frasten** [comment]
Sure: http://pastie.org/4858170 :-)

**Comment by kubitron** [comment]
Ok.  Thanks for your patience.  I don't believe that I've seen this problem before.

I just uploaded more debugging on the debugging branch.  When you start things up, you should see:

```
<<<<<<<<<<<<Post-install checks!>>>>>>>>>>>>>>>
Running git_cmd_with_sudo
check_git_cmd_connect is properly defined
Running git_cmd_with_sudo
git_cmd_without_sudo exists!
git_cmd_with_sudo exists!
git_cmd still aliased to git_cmd_with_sudo
```

You should also be able to run fetch_changesets manually:

```
sudo -u apache rake redmine_git_hosting:fetch_changesets RAILS_ENV=production
```

(or whatever your web server is instead of 'apache'). You will see complaints of "fatal: Not a git repository: ''.  This is expected.

In the log, you should then see lots of debugging.  

```
<<<<<<<<<<<<Fetch Changesets check of git_cmd redirection!>>>>>>>>>>>>>>>
Running git_cmd_with_sudo
About to execute CachedShellRedirector(''/source/tessellation/test-site/redmine/vendor/plugins/redmine_git_hosting/bin/run_git_as_git_user' '--git-dir' '' 'log' '--no-color' '--encoding=UTF-8' '--date=iso' '--pretty=fuller' '--no-merges'  '-n' '1'','')
check_git_cmd_connect is properly defined
Running git_cmd_with_sudo
About to execute CachedShellRedirector(''/source/tessellation/test-site/redmine/vendor/plugins/redmine_git_hosting/bin/run_git_as_git_user' '--git-dir' '' 'log' '--no-color' '--encoding=UTF-8' '--date=iso' '--pretty=fuller' '--no-merges'  '-n' '1'','')
git_cmd_without_sudo exists!
git_cmd_with_sudo exists!
git_cmd still aliased to git_cmd_with_sudo
Running git_cmd_with_sudo
About to execute CachedShellRedirector(''/source/tessellation/test-site/redmine/vendor/plugins/redmine_git_hosting/bin/run_git_as_git_user' '--git-dir' 'repositories/tess-kernel.git' 'branch' '--no-color' '--verbose' '--no-abbrev'','tess-kernel')
```

Notice that the key aspect is "git_cmd still aliased to git_cmd_with_sudo".

**Comment by kubitron** [comment]
Incidentally, did you do a clean install here?  I realize that you had other plugins.  Could there be remnants of the code in the plugins subtree still?

**Comment by frasten** [comment]
Here are the results:
Log while clicking on Repository: http://pastie.org/4859764
Log while doing manual fetch via command line: http://pastie.org/4859765

Unfortunately it says: `git_cmd not still aliased to git_cmd_with_sudo`.

The output for that command is:

```
root@hydraulics-prod:/home/redmine/redmine# sudo -u apache rake redmine_git_hosting:fetch_changesets RAILS_ENV=production
Please install RDoc 2.4.2+ to generate documentation.
[Performing manual fetch_changesets operation...
fatal: Not a git repository: ''
fatal: Not a git repository: ''
fatal: Not a git repository: 'repositories/hydralisk.git'
DONE.]
```

Note the two new empty repositories, but those could be due to the new debugging code (in the `repositories` table in the DB there is only one record, and it is repositories/hydralisk.git).

Regarding the second question, actually I reinstalled Redmine (new and clean db and directories) because I was having this issue, and I was trying to fix it.
My `vendor/plugins` is clean:

```
drwxrwxr-x  3 apache apache 4,0K 18 giu 22:24 acts_as_activity_provider
drwxrwxr-x  3 apache apache 4,0K 18 giu 22:23 acts_as_attachable
drwxrwxr-x  3 apache apache 4,0K 18 giu 22:23 acts_as_customizable
drwxrwxr-x  3 apache apache 4,0K 18 giu 22:24 acts_as_event
drwxrwxr-x  4 apache apache 4,0K 18 giu 22:24 acts_as_list
drwxrwxr-x  3 apache apache 4,0K 18 giu 22:23 acts_as_searchable
drwxrwxr-x  4 apache apache 4,0K 18 giu 22:23 acts_as_tree
drwxrwxr-x  4 apache apache 4,0K 18 giu 22:23 acts_as_versioned
drwxrwxr-x  3 apache apache 4,0K 18 giu 22:23 acts_as_watchable
drwxrwxr-x  5 apache apache 4,0K 18 giu 22:24 awesome_nested_set
drwxrwxr-x  4 apache apache 4,0K 18 giu 22:23 classic_pagination
drwxrwxr-x  5 apache apache 4,0K 18 giu 22:23 engines
drwxrwxr-x  4 apache apache 4,0K 18 giu 22:24 gravatar
drwxrwxr-x  5 apache apache 4,0K 18 giu 22:24 open_id_authentication
drwxrwxr-x  2 apache apache 4,0K 18 giu 22:23 prepend_engine_views
drwxr-xr-x 13 apache apache 4,0K 29 set 10:56 redmine_git_hosting
drwxrwxr-x  4 apache apache 4,0K 18 giu 22:24 rfpdf
```

These are only default plugins, plus redmine_git_hosting.
Thank you! :-)

**Comment by kubitron** [comment]
Ok.  I have one last try before I try more extensive debugging.  Last version, I changed the way that patches were integrated into Redmine.  It is possible that this was problematic.  

I updated both the testing branch and the debugging branch.  The debugging branch was a forced update (to incorporate the new changes).  Could you try either (1) pulling testing and trying it again or (2) clobbering the last couple of commits on the debugging branch and pulling again?  

You can do the latter (staying on the debugging branch) like this:

```
% git reset --hard HEAD~2
% git pull
```

If you do the latter (probably the best idea), you could repeat that previous experiment to see if things work better...

Really sorry about the mess.  You are being a good sport.

**Comment by frasten** [comment]
Unfortunately, things aren't better:

### Test 1 (testing branch, commit d2c0029)
- Log while clicking on Repository: http://pastie.org/4861510
- Log while doing manual fetch via command line: http://pastie.org/4861535

### Test 2 (debugging branch, commit cd6de31)
- Log while clicking on Repository: http://pastie.org/4861537
- Log while doing manual fetch via command line: http://pastie.org/4861540

Thank you for your patience! :-)

**Comment by kubitron** [comment]
Tell me again (1) you exact sequence of installation and (2) what your deployment platform is?

**Comment by frasten** [comment]
1) Sequence of installation:
- Set sudo permissions for user `git` and `apache`, via `visudo`
- Copy gitolite admin keys under /home/redmine/redmine/.ssh/gitolite_admin_id_rsa*
- Clone redmine_git_hosting under /home/redmine/redmine/vendor/plugins/redmine_git_hosting/
- Set init.rb setting `httpServer` and `gitServer` to `hydraulics-prod.ing.unibs.it` and `httpServerSubdir` to `'redmine/'`
- Apply my usual reset sequence:

```
rm -rf /tmp/redmine_git_hosting
cd /home/redmine/redmine
rake redmine_git_hosting:remove_scripts RAILS_ENV=production
rake redmine_git_hosting:restore_defaults RAILS_ENV=production
rake db:migrate_plugins RAILS_ENV=production
rake redmine_git_hosting:install_scripts RAILS_ENV=production WEB_USER=apache
chown -R apache:apache /home/redmine/redmine
sudo -u apache rake redmine_git_hosting:update_repositories RAILS_ENV=production
sudo -u apache rake redmine_git_hosting:fetch_changesets RAILS_ENV=production
/etc/init.d/httpd start
```

2) My deployment platform:
- CentOS release 6.3
- Redmine 1.4.4
- Git 1.7.1
- Gitolite 2.3.1
- Apache 2.2.15
- Passenger 3.0.17
- Ruby 1.8.7
- Rails 2.3.14
- RubyGems 1.8.21
- My script/about: http://pastie.org/4863197

Thank you!

**Comment by kubitron** [comment]
Ok.  Can we try another experiment in the debugging branch?

Add the following to the top of REDMINE_ROOT/lib/redmine/scm/adapters/git_adapter.rb:

```
Rails.logger.error "\n\n<<<<<<<<<Loading git_adapter!>>>>>>>>>>>>>"
begin
    raise
rescue => e
    Rails.logger.error e.backtrace.join("\n")
end
Rails.logger.error "<<<<<<<<<Done with backtrace!>>>>>>>>>>>>>"
```

Note that I'm having you add this, since it is in the main redmine codebase. Then, restart and try loading a repository.  Show me the resulting log (from the time that you reboot the application).  There will be a lot of debugging messages (just trying to figure out how the git_adapter.rb gets reloaded).

Thanx....

**Comment by kubitron** [comment]
Ok. I finally reproduced the problem!  I think it is due to a different ordering of patches on our two different installations.

Could you try loading the testing branch (may need to kill off last couple of commits) and see if things work?  Hopefully they will.  If not, then reload the debugging branch (again, need to force it) and also apply the above patch to git_adapter.rb and let me know what comes out.

**Comment by frasten** [comment]
Hurray! Commit 0a2ad16 fixes this issue for me!!!!
Also, some commit between 2591c8f and 0a2ad16 fixes #69 for me!
Now I'm completely happy with this plugin, you did an amazing job debugging this bug! 
I'll try to test the plugin as I can to repay for your efforts! :-)
Thank you!

**Comment by kubitron** [comment]
Yeah!  Sorry that it took so long to fix.  Makes perfect sense, in retrospect, but ack!

I'm glad that it fixes #69 as well.  That one is a mystery and hopefully fixed for more than just you (not problem with me).

Testing is much appreciated.  I would love to make this a non-testing branch soon.

**Comment by kubitron** [comment]
Say @frasten -- anything new?  Is the plugin working for you?  I am hoping to export it to the master branch soon.

**Comment by frasten** [comment]
I didn't find any new bug, the testing branch is working really well with Redmine 1.4*.
Thank you!

**Comment by kubitron** [comment]
Great!  Make sure to register any new bugs you find.  I will probably switch this over to the master branch soon.

**Comment by lauer** [comment]
Great, then please make it work with 2.0 (2.1) - I am really missing the plugin. I was upgrading last week from redmine 1.4 to 2.1, because this plugin didn't work with 1.4 anyway. I would be happy to help with testing.

**Comment by kubitron** [comment]
@lauer, sorry that I got a bit behind with updates.

Update to 2.0 shouldn't be too bad (biggest worry is about Prototype=>jQuery change).  Should happen soon.  

If you haven't quite upgraded yet, you might give this latest version (1.4) a spin.

**Comment by kubitron** [comment]
Hello all -- just checking in.

Can you make sure to pull from head of master?  I had to add some patches to restore pre 1.4 operation and wanted to make sure that they didn't mess things up with Redmine 1.4 support.

**Comment by frasten** [comment]
Don't worry, I've been always updating my clone every day against the remote master HEAD, and it is working flawlessly under Redmine 1.4.4.
