### ISSUE TITLE
Crash when adding repository in repo

### ISSUE THREAD

**Issue by niosHD** [kubitron/redmine_git_hosting#82]
Hello again!

Unfortunately I found more problems which seem to be related with the current master version on a Redmine 1.3.x release.

The git hosting plugin is configured with "Automatically Initialize Git Repositories For New Projects = Disabled".Creating a new project works just as expected. However, when I decide that I want to add a git repository afterwards (Project Settings -> Repository) the plugin crashes with the following error message:

```
Processing RepositoriesController#edit (for 193.170.226.203 at 2012-10-15 19:42:50) [GET]
  Parameters: {"action"=>"edit", "repository_scm"=>"Git", "authenticity_token"=>"EGjQ4le2LsyjJ/TdesFL8aOtlFiDpoxhpj7tPAassOQ=", "id"=>"test2", "commit"=>"Create", "controller"=>"repositories", "repository"=>{"url"=>"", "log_encoding"=>""}}

NoMethodError (undefined method `git_label' for #<Project:0x93ff3f0>):
  passenger (3.0.11) lib/phusion_passenger/rack/request_handler.rb:96:in `process_request'
[...]
  passenger (3.0.11) helper-scripts/passenger-spawn-server:99

Rendering /var/redmine-1.3.2/public/500.html (500 Internal Server Error)
```

When I tried to work around this bug by using  "Automatically Initialize Git Repositories For New Projects = Enabled" I encountered another problem (probably unrelated to the first one) which is described in the second bug report.

**Comment by niosHD** [comment]
Just to make it clearer. The crash occurs when GIT is selected from the drop down menu on the Repository Settings Page.

**Comment by kubitron** [comment]
Ok.  Have reproduced.  One moment.

**Comment by kubitron** [comment]
Pull from master and see if this fixes problem (it should).

**Comment by niosHD** [comment]
Works now. Thanks!

**Comment by kubitron** [comment]
Great!  Glad that it is working.
