### ISSUE TITLE
Automatic creation/setup of mirror repositories

### ISSUE THREAD

**Issue by phindmarsh** [kubitron/redmine_git_hosting#9]
We use this version of redmine_git_hosting for our small development shop. We also have a bitbucket.org account that we sync a mirror of all our repositories to (in case something goes really wrong at our end).

At present when we create a new project we also log into bitbucket and make a new project then configure the mirror to sync to it. 

What I propose is one of two things:
- Create some common API connectors for popular third party git hosting services that can be hit when a new project is created and setup the remote repository and configure the mirror locally.
- Provide some sort of 'post_project_created' hook that calls a local script (similar idea to a post-receive hook in git), so the logic for creating the mirror repositories is left to end users like myself :)

Bitbucket has a good API for checking/creating repositories, and if this feature was to be implemented it would be peace of mind backups that we don't have to actively setup/monitor.

Hope this makes sense, I'm not a rails guy otherwise I'd attempt this myself. I made a rudimentary version in bash that was called via a post-receive git hook, but the problem was it would hold up every commit while it communicated with bitbucket. The mirrors functionality is so much nicer, all it needs now is auto-setup!

Thanks for your time on this plugin, it is certainly very very useful!

**Comment by phindmarsh** [comment]
(BTW, doesn't look like I can apply the Feature Request label, it doesn't appear on the right for me)

**Comment by kubitron** [comment]
Ok. Just out of curiosity -- do you use the mirror functionality built into this plugin?  As far as I can tell, it was pretty broken in previous versions of the plugin (I just fixed some pretty blatant bugs).  The current mirror function (with some patches) only synchronizes on a mirror when you push the synchronize button (or whatever it is called) on the UI.  Is that still what you are proposing?

(i.e. the only thing in this request is to somehow setup a new mirror both remotely and locally...?)

**Comment by phindmarsh** [comment]
It was my understanding that the mirrors were synced when a push to the repository was made (and I think I recall seeing this behaviour).

I was digging though the post-recieve hooks of the other versions of this plugin and it seemed to be doing stuff with mirrors so I assumed it was after a push that they were triggered.

Ideally, if this functionality still exists, the idea is to have an automatic, behind-the-scences mirror/backup of every repository as it is updated.

**Comment by kubitron** [comment]
Ok.  I don't use mirrors right now, so not clear on the behavior.  Perhaps you could try them out using my current master branch and see if the behave the way you expect?  

I'm in the middle of something right now, but I'll keep this feature request in mind when I get a chance.

**Comment by phindmarsh** [comment]
I just created a new project (using your master branch) and configured a mirror on bitbucket. 

When pushing to the redmine hosted repository, it automatically pushed to the mirror on bitbucket. I stumbled across a script I wrote that creates and pushes to bitbucket as an `update` hook (the disadvantage of this is the 'mirror' ends up being one commit behind the main repository, and its not asynchronous).

``` bash
repobase=$GL_REPO_BASE_ABS
repofilename=$GL_REPO
reponame=${repofilename##*\/}
username="myusername"
password="mypassword"
API_URL="https://api.bitbucket.org/1.0/"

echo "Updating $reponame to bitbucket: "$API_URL"repositories/"$username"/"$reponame

response=$(curl -u $username:$password --write-out %{http_code} --silent --output /dev/null $API_URL"repositories/"$username"/"$reponame)

if [ $response == "404" ]; then
    echo "Creating new repository '$reponame'... "
    response=$(curl -X POST \
        -u $username:$password \
        --write-out %{http_code} \
        --silent --output /dev/null \
        https://api.bitbucket.org/1.0/repositories/ -d name=$reponame -d scm=git -d is_private=True)
    if [ $response != "200" ]; then
        echo "Fatal, could not create repository"
        exit
    fi
fi
```

So I think the feature as it stands would be one of two things:
- An optional ability to configure mirrors automatically if they don't exist already
- Modify the way the hooks work (I tried this and just cheesed it up) so custom hooks can be written for post-recieve actions. I think this is more of a gitolite thing than the redmine thing (at a guess).

**Comment by kubitron** [comment]
Just to clarity: are you saying that the unmodified behavior of mirrors with this plugin is to automagically push every update to the mirror?  Or, is your update hook necessary to get that basic bahavior?

(Or, is the update hook only for creating the new mirror repository)?

**Comment by phindmarsh** [comment]
Correct, the functionality at present is that the mirrors are automatically pushed to when the main repository is updated (sorry I was unclear before). The bit that doesn't exist is the creation of that mirror repository to push to.

The code I provided is an example of automatically creating a new repository on bitbucket when it doesn't exist. It was a component of my previous attempt at solving this without changing the plugin (which was unsuccessful).

**Comment by kubitron** [comment]
Since you are not using this plugin anymore, I'm going to retire this feature request. I hope that is ok.  It seems pretty specialized, and I want to move on to 1.4/2.0 compatibility.
